/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApplyProjectWorkerRecruitmentRequest
 */
export interface ApplyProjectWorkerRecruitmentRequest {
    /**
     * 1주일 기준 작업 가능 시간
     * @type {number}
     * @memberof ApplyProjectWorkerRecruitmentRequest
     */
    'workHourPerWeek': number;
    /**
     * 자기소개
     * @type {string}
     * @memberof ApplyProjectWorkerRecruitmentRequest
     */
    'introduce': string;
    /**
     * 현재 진행 중인 프로젝트
     * @type {string}
     * @memberof ApplyProjectWorkerRecruitmentRequest
     */
    'currentProjectStatus': string;
    /**
     * 기술스택과 유관한 프로젝트 경험
     * @type {string}
     * @memberof ApplyProjectWorkerRecruitmentRequest
     */
    'projectExperience': string;
    /**
     * 스스로 생각한 자기 실력
     * @type {string}
     * @memberof ApplyProjectWorkerRecruitmentRequest
     */
    'ownSkill': string;
    /**
     * 협업 경험
     * @type {string}
     * @memberof ApplyProjectWorkerRecruitmentRequest
     */
    'coWorkingExperience': string;
    /**
     * 다른 플랫폼 외주 경험 여부
     * @type {string}
     * @memberof ApplyProjectWorkerRecruitmentRequest
     */
    'outsourceWithOtherPlatform': string;
    /**
     * 문의사항
     * @type {string}
     * @memberof ApplyProjectWorkerRecruitmentRequest
     */
    'question'?: string;
    /**
     * 작업 범위 확인
     * @type {string}
     * @memberof ApplyProjectWorkerRecruitmentRequest
     */
    'workScopeText': string;
}

