/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface BaseResponseVoid
 */
export interface BaseResponseVoid {
    /**
     * 요청 성공 여부
     * @type {boolean}
     * @memberof BaseResponseVoid
     */
    'isSuccess'?: boolean;
    /**
     * 요청 결과 코드
     * @type {number}
     * @memberof BaseResponseVoid
     */
    'code'?: number;
    /**
     * 요청 메시지
     * @type {string}
     * @memberof BaseResponseVoid
     */
    'message'?: string;
    /**
     * 내용
     * @type {object}
     * @memberof BaseResponseVoid
     */
    'result'?: object;
}

