/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetRoleListResponse } from './get-role-list-response';

/**
 * 
 * @export
 * @interface BaseResponseGetRoleListResponse
 */
export interface BaseResponseGetRoleListResponse {
    /**
     * 요청 성공 여부
     * @type {boolean}
     * @memberof BaseResponseGetRoleListResponse
     */
    'isSuccess'?: boolean;
    /**
     * 요청 결과 코드
     * @type {number}
     * @memberof BaseResponseGetRoleListResponse
     */
    'code'?: number;
    /**
     * 요청 메시지
     * @type {string}
     * @memberof BaseResponseGetRoleListResponse
     */
    'message'?: string;
    /**
     * 내용
     * @type {GetRoleListResponse}
     * @memberof BaseResponseGetRoleListResponse
     */
    'result'?: GetRoleListResponse;
}

