/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CheckPhoneVerifyRequest
 */
export interface CheckPhoneVerifyRequest {
    /**
     * 전화번호<br>해외 번호의 경우도 특수문자 없이 숫자만 입력
     * @type {string}
     * @memberof CheckPhoneVerifyRequest
     */
    'phoneNumber': string;
    /**
     * 인증번호
     * @type {string}
     * @memberof CheckPhoneVerifyRequest
     */
    'verificationCode': string;
}

