/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetEmailVerifyResponse
 */
export interface GetEmailVerifyResponse {
    /**
     * 이메일 중복 검사 통과 여부 (true, false)<br>통과하면 true를 반환한다
     * @type {boolean}
     * @memberof GetEmailVerifyResponse
     */
    'isVerify': boolean;
}

