/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetSendEmailResponse
 */
export interface GetSendEmailResponse {
    /**
     * 알림톡 전송 여부 (true, false)
     * @type {boolean}
     * @memberof GetSendEmailResponse
     */
    'isSuccess': boolean;
}

