/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectWorkerRecruitmentDto } from './project-worker-recruitment-dto';

/**
 * 
 * @export
 * @interface GetProjectWorkerRecruitmentResponse
 */
export interface GetProjectWorkerRecruitmentResponse {
    /**
     * 
     * @type {ProjectWorkerRecruitmentDto}
     * @memberof GetProjectWorkerRecruitmentResponse
     */
    'recruitment': ProjectWorkerRecruitmentDto;
}

