/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectContractDto } from './project-contract-dto';

/**
 * 
 * @export
 * @interface GetProjectContractListResponse
 */
export interface GetProjectContractListResponse {
    /**
     * 
     * @type {Array<ProjectContractDto>}
     * @memberof GetProjectContractListResponse
     */
    'projectContractList': Array<ProjectContractDto>;
}

