/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { RevisionFieldResponseBigDecimal } from './revision-field-response-big-decimal';
// May contain unused imports in some cases
// @ts-ignore
import type { RevisionFieldResponseInteger } from './revision-field-response-integer';
// May contain unused imports in some cases
// @ts-ignore
import type { RevisionFieldResponseLocalDate } from './revision-field-response-local-date';
// May contain unused imports in some cases
// @ts-ignore
import type { RevisionFieldResponseWorkerContractPaymentType } from './revision-field-response-worker-contract-payment-type';

/**
 * 
 * @export
 * @interface GetProjectWorkerContractTimelineResponse
 */
export interface GetProjectWorkerContractTimelineResponse {
    /**
     * 작업자 계약 변경 내역 ID
     * @type {number}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'revisionId'?: number;
    /**
     * 작업자 계약 타임라인 시점
     * @type {string}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'timeline'?: string;
    /**
     * 작업자 계약 ID
     * @type {number}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'projectWorkerContractId'?: number;
    /**
     * 작업자 계약 변경 유형
     * @type {string}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'projectWorkerContractTimelineType'?: GetProjectWorkerContractTimelineResponseProjectWorkerContractTimelineTypeEnum;
    /**
     * 작업자 계약 시작 날짜
     * @type {string}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'contractStartDate'?: string;
    /**
     * 작업자 계약 종료 날짜
     * @type {string}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'contractEndDate'?: string;
    /**
     * 작업자 계약 지급 시간당 임금
     * @type {number}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'payHourlyWage'?: number;
    /**
     * 작업자 계약 지급 월별 임금
     * @type {number}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'payMonthlyWage'?: number;
    /**
     * 작업자 계약 결제 유형
     * @type {string}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'contractPaymentType'?: GetProjectWorkerContractTimelineResponseContractPaymentTypeEnum;
    /**
     * 작업자 계약 근무 예상 시간 주간 최소 시간
     * @type {number}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'weeklyMinUsageHours'?: number;
    /**
     * 작업자 계약 근무 예상 시간 주간 평균 시간
     * @type {number}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'weeklyAverageUsageHours'?: number;
    /**
     * 작업자 계약 근무 예상 시간 주간 최대 시간
     * @type {number}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'weeklyMaxUsageHours'?: number;
    /**
     * 작업자 계약 특약 ID
     * @type {number}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'projectWorkerContractTermId'?: number;
    /**
     * 작업자 계약 특약 시작 날짜
     * @type {string}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'termStartDate'?: string;
    /**
     * 작업자 계약 특약 종료 날짜
     * @type {string}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'termEndDate'?: string;
    /**
     * 작업자 계약 시작 날짜 변경 정보
     * @type {RevisionFieldResponseLocalDate}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'revisionOfContractStartDate'?: RevisionFieldResponseLocalDate;
    /**
     * 작업자 계약 종료 날짜 변경 정보
     * @type {RevisionFieldResponseLocalDate}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'revisionOfContractEndDate'?: RevisionFieldResponseLocalDate;
    /**
     * 작업자 계약 결제 유형 변경 정보
     * @type {RevisionFieldResponseWorkerContractPaymentType}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'revisionOfContractPaymentType'?: RevisionFieldResponseWorkerContractPaymentType;
    /**
     * 작업자 계약 지급 시간당 임금 변경 정보 <br>작업자 지급 금액 변경 정보는 관리자, 작업자만 확인할 수 있습니다
     * @type {RevisionFieldResponseInteger}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'revisionOfPayHourlyWage'?: RevisionFieldResponseInteger;
    /**
     * 작업자 계약 지급 월별 임금 변경 정보 <br>작업자 지급 금액 변경 정보는 관리자, 작업자만 확인할 수 있습니다
     * @type {RevisionFieldResponseInteger}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'revisionOfPayMonthlyWage'?: RevisionFieldResponseInteger;
    /**
     * 작업자 계약 근무 예상 시간 주간 최소 시간 변경 정보
     * @type {RevisionFieldResponseBigDecimal}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'revisionOfWeeklyMinUsageHours'?: RevisionFieldResponseBigDecimal;
    /**
     * 작업자 계약 근무 예상 시간 주간 평균 시간 변경 정보
     * @type {RevisionFieldResponseBigDecimal}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'revisionOfWeeklyAverageUsageHours'?: RevisionFieldResponseBigDecimal;
    /**
     * 작업자 계약 근무 예상 시간 주간 최대 시간 변경 정보
     * @type {RevisionFieldResponseBigDecimal}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'revisionOfWeeklyMaxUsageHours'?: RevisionFieldResponseBigDecimal;
    /**
     * 비고 메시지 (특약에 대한 추가 정보 등)
     * @type {string}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'etc'?: string;
    /**
     * 작업자 확인 여부
     * @type {boolean}
     * @memberof GetProjectWorkerContractTimelineResponse
     */
    'nerdUserChecked'?: boolean;
}

export const GetProjectWorkerContractTimelineResponseProjectWorkerContractTimelineTypeEnum = {
    Initial: 'INITIAL',
    AddProjectWorkerContractTerm: 'ADD_PROJECT_WORKER_CONTRACT_TERM',
    UpdateProjectWorkerContract: 'UPDATE_PROJECT_WORKER_CONTRACT',
    ProjectWorkerContractComplete: 'PROJECT_WORKER_CONTRACT_COMPLETE',
    ProjectWorkerContractTerminate: 'PROJECT_WORKER_CONTRACT_TERMINATE',
    ProjectWorkerContractFinished: 'PROJECT_WORKER_CONTRACT_FINISHED'
} as const;

export type GetProjectWorkerContractTimelineResponseProjectWorkerContractTimelineTypeEnum = typeof GetProjectWorkerContractTimelineResponseProjectWorkerContractTimelineTypeEnum[keyof typeof GetProjectWorkerContractTimelineResponseProjectWorkerContractTimelineTypeEnum];
export const GetProjectWorkerContractTimelineResponseContractPaymentTypeEnum = {
    Allinone: 'ALLINONE',
    Subscription: 'SUBSCRIPTION',
    MonthlySubscription: 'MONTHLY_SUBSCRIPTION'
} as const;

export type GetProjectWorkerContractTimelineResponseContractPaymentTypeEnum = typeof GetProjectWorkerContractTimelineResponseContractPaymentTypeEnum[keyof typeof GetProjectWorkerContractTimelineResponseContractPaymentTypeEnum];


