/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GetProjectWorkerContractTimelineResponse } from './get-project-worker-contract-timeline-response';

/**
 * 
 * @export
 * @interface GetProjectWorkerContractHistoryResponse
 */
export interface GetProjectWorkerContractHistoryResponse {
    /**
     * 프로젝트 계약 ID
     * @type {number}
     * @memberof GetProjectWorkerContractHistoryResponse
     */
    'projectContractId'?: number;
    /**
     * 프로젝트 작업자 ID
     * @type {number}
     * @memberof GetProjectWorkerContractHistoryResponse
     */
    'projectWorkerId'?: number;
    /**
     * 작업자 ID (Nerd User ID)
     * @type {number}
     * @memberof GetProjectWorkerContractHistoryResponse
     */
    'nerdUserId'?: number;
    /**
     * 작업자 실명
     * @type {string}
     * @memberof GetProjectWorkerContractHistoryResponse
     */
    'realName'?: string;
    /**
     * 작업자 닉네임
     * @type {string}
     * @memberof GetProjectWorkerContractHistoryResponse
     */
    'nickName'?: string;
    /**
     * 작업자 역할 ID
     * @type {number}
     * @memberof GetProjectWorkerContractHistoryResponse
     */
    'roleId'?: number;
    /**
     * 작업자 역할 이름
     * @type {string}
     * @memberof GetProjectWorkerContractHistoryResponse
     */
    'roleName'?: string;
    /**
     * 
     * @type {Array<GetProjectWorkerContractTimelineResponse>}
     * @memberof GetProjectWorkerContractHistoryResponse
     */
    'projectWorkerContractTimeline'?: Array<GetProjectWorkerContractTimelineResponse>;
}

