/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobCategoryIdDto } from './job-category-id-dto';

/**
 * 
 * @export
 * @interface NerdSignUpRequest
 */
export interface NerdSignUpRequest {
    /**
     * 이름
     * @type {string}
     * @memberof NerdSignUpRequest
     */
    'name': string;
    /**
     * 닉네임
     * @type {string}
     * @memberof NerdSignUpRequest
     */
    'nickname': string;
    /**
     * 이메일
     * @type {string}
     * @memberof NerdSignUpRequest
     */
    'email': string;
    /**
     * 비밀번호
     * @type {string}
     * @memberof NerdSignUpRequest
     */
    'password': string;
    /**
     * 국가 코드
     * @type {string}
     * @memberof NerdSignUpRequest
     */
    'regionCode': string;
    /**
     * 인증번호
     * @type {string}
     * @memberof NerdSignUpRequest
     */
    'verificationCode': string;
    /**
     * 직군/직무 아이디
     * @type {Array<JobCategoryIdDto>}
     * @memberof NerdSignUpRequest
     */
    'jobCategoryList': Array<JobCategoryIdDto>;
    /**
     * 프레임워크 아이디 목록
     * @type {Array<number>}
     * @memberof NerdSignUpRequest
     */
    'frameworkIdList'?: Array<number>;
    /**
     * 언어 아이디 목록
     * @type {Array<number>}
     * @memberof NerdSignUpRequest
     */
    'languageIdList'?: Array<number>;
    /**
     * 개인정보 처리 동의 여부
     * @type {boolean}
     * @memberof NerdSignUpRequest
     */
    'isPrivacyAccepted': boolean;
    /**
     * 마케팅 수신 동의 여부
     * @type {boolean}
     * @memberof NerdSignUpRequest
     */
    'isMarketingAccepted': boolean;
}

