/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectWorkHistoryDetailDto } from './project-work-history-detail-dto';

/**
 * 
 * @export
 * @interface PageResponseProjectWorkHistoryDetailDto
 */
export interface PageResponseProjectWorkHistoryDetailDto {
    /**
     * 조회 한 페이지 번호
     * @type {number}
     * @memberof PageResponseProjectWorkHistoryDetailDto
     */
    'page'?: number;
    /**
     * 설정한 페이지 당 조회 갯수
     * @type {number}
     * @memberof PageResponseProjectWorkHistoryDetailDto
     */
    'size'?: number;
    /**
     * 총 항목 수
     * @type {number}
     * @memberof PageResponseProjectWorkHistoryDetailDto
     */
    'totalElements'?: number;
    /**
     * 총 페이지 수
     * @type {number}
     * @memberof PageResponseProjectWorkHistoryDetailDto
     */
    'totalPages'?: number;
    /**
     * 다음 페이지 존재 여부
     * @type {boolean}
     * @memberof PageResponseProjectWorkHistoryDetailDto
     */
    'hasNextPage'?: boolean;
    /**
     * 객체 목록
     * @type {Array<ProjectWorkHistoryDetailDto>}
     * @memberof PageResponseProjectWorkHistoryDetailDto
     */
    'contents'?: Array<ProjectWorkHistoryDetailDto>;
}

