/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchProjectMilestoneTaskStatusRequest
 */
export interface PatchProjectMilestoneTaskStatusRequest {
    /**
     * 프로젝트 테스크 상태 (NOT_STARTED: 진행 전, IN_PROGRESS: 진행 중, EDITING: 수정 중, DONE: 컨펌 완료)
     * @type {string}
     * @memberof PatchProjectMilestoneTaskStatusRequest
     */
    'taskStatus': string;
}

