/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PatchProjectMilestoneRequest
 */
export interface PatchProjectMilestoneRequest {
    /**
     * 프로젝트 마일스톤 이름
     * @type {string}
     * @memberof PatchProjectMilestoneRequest
     */
    'milestoneName': string;
    /**
     * 프로젝트 마일스톤 달성 목표
     * @type {string}
     * @memberof PatchProjectMilestoneRequest
     */
    'milestoneObjective': string;
    /**
     * 마일스톤 시작일
     * @type {string}
     * @memberof PatchProjectMilestoneRequest
     */
    'milestoneStartDate'?: string;
    /**
     * 마일스톤 마감일
     * @type {string}
     * @memberof PatchProjectMilestoneRequest
     */
    'milestoneEndDate'?: string;
}

