/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostUserPortfolioRequest
 */
export interface PostUserPortfolioRequest {
    /**
     * 파일명 (.png, .jpg, .jpeg, .pdf)
     * @type {string}
     * @memberof PostUserPortfolioRequest
     */
    'fileName': string;
    /**
     * 파일 크기
     * @type {number}
     * @memberof PostUserPortfolioRequest
     */
    'fileLength': number;
}

