/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostProjectWorkHistoryRequest
 */
export interface PostProjectWorkHistoryRequest {
    /**
     * 테스크 ID<br>테스크가 존재하는 경우에만 입력해주세요.
     * @type {number}
     * @memberof PostProjectWorkHistoryRequest
     */
    'taskId': number;
    /**
     * 테스크 담당 작업자 ID
     * @type {number}
     * @memberof PostProjectWorkHistoryRequest
     */
    'projectWorkerId': number;
    /**
     * 작업 내용 ID<br>작업 내용 ID 혹은 작업 내용 텍스트 둘 중 하나를 반드시 입력해야 합니다.
     * @type {number}
     * @memberof PostProjectWorkHistoryRequest
     */
    'workDescriptionId'?: number;
    /**
     * 작업 내용<br>작업 내용 ID 혹은 작업 내용 텍스트 둘 중 하나를 반드시 입력해야 합니다.
     * @type {string}
     * @memberof PostProjectWorkHistoryRequest
     */
    'workDescription'?: string;
    /**
     * 업무 시작 일시
     * @type {string}
     * @memberof PostProjectWorkHistoryRequest
     */
    'workStartAt': string;
    /**
     * 업무 종료 일시
     * @type {string}
     * @memberof PostProjectWorkHistoryRequest
     */
    'workEndAt'?: string;
    /**
     * 작업 진행률
     * @type {number}
     * @memberof PostProjectWorkHistoryRequest
     */
    'progressPercent'?: number;
}

