/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PostProjectHistoryRequest
 */
export interface PostProjectHistoryRequest {
    /**
     * 작업한 테스크 ID
     * @type {number}
     * @memberof PostProjectHistoryRequest
     */
    'projectMilestoneTaskId': number;
    /**
     * 테스크 담당 작업자 ID
     * @type {number}
     * @memberof PostProjectHistoryRequest
     */
    'projectWorkerId'?: number;
    /**
     * 작업 내용
     * @type {string}
     * @memberof PostProjectHistoryRequest
     */
    'workDescription': string;
    /**
     * 업무 시작 일시
     * @type {string}
     * @memberof PostProjectHistoryRequest
     */
    'workStartAt': string;
    /**
     * 업무 종료 일시
     * @type {string}
     * @memberof PostProjectHistoryRequest
     */
    'workEndAt': string;
    /**
     * 작업 진행률
     * @type {number}
     * @memberof PostProjectHistoryRequest
     */
    'progressPercent': number;
    /**
     * 산출물 링크
     * @type {string}
     * @memberof PostProjectHistoryRequest
     */
    'outputUrl'?: string;
}

