/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectRoleDto } from './project-role-dto';

/**
 * 
 * @export
 * @interface ProjectWorkerRecruitmentDto
 */
export interface ProjectWorkerRecruitmentDto {
    /**
     * 외주 공고 아이디
     * @type {number}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'id': number;
    /**
     * 직무
     * @type {ProjectRoleDto}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'role': ProjectRoleDto;
    /**
     * 외주 공고명
     * @type {string}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'title': string;
    /**
     * 계약 시작 날짜
     * @type {string}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'contractStartDate'?: string;
    /**
     * 계약 종료 날짜
     * @type {string}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'contractEndDate'?: string;
    /**
     * 좋아요 여부
     * @type {boolean}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'isLiked': boolean;
    /**
     * 공고 상태 (WAIT: 대기, IN_PROGRESS: 모집중, REVIEW: 검토중, COMPLETE: 매칭완료, CANCELLED: 취소)
     * @type {string}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'recruitmentStatus': ProjectWorkerRecruitmentDtoRecruitmentStatusEnum;
    /**
     * 예상 수입
     * @type {number}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'expectedWage'?: number;
    /**
     * 남은 지원자 수
     * @type {number}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'leftApplyCnt': number;
    /**
     * 프로젝트 의뢰서 링크
     * @type {string}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'detailFileUrl'?: string;
    /**
     * 첫 번째 지원자 (마스킹 처리)
     * @type {string}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'firstApplicant'?: string;
    /**
     * 지원자/참여자 수
     * @type {number}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'applyCnt': number;
    /**
     * 그릿지 한마디
     * @type {string}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'projectSummary'?: string;
    /**
     * 핵심 기술
     * @type {string}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'projectRequirement'?: string;
    /**
     * 외주 공고 지원 여부 (true/false)
     * @type {boolean}
     * @memberof ProjectWorkerRecruitmentDto
     */
    'isApplied'?: boolean;
}

export const ProjectWorkerRecruitmentDtoRecruitmentStatusEnum = {
    Wait: 'WAIT',
    InProgress: 'IN_PROGRESS',
    Reviewing: 'REVIEWING',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;

export type ProjectWorkerRecruitmentDtoRecruitmentStatusEnum = typeof ProjectWorkerRecruitmentDtoRecruitmentStatusEnum[keyof typeof ProjectWorkerRecruitmentDtoRecruitmentStatusEnum];


