/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectContractDto
 */
export interface ProjectContractDto {
    /**
     * 프로젝트 계약 ID
     * @type {number}
     * @memberof ProjectContractDto
     */
    'id': number;
    /**
     * 프로젝트 ID
     * @type {number}
     * @memberof ProjectContractDto
     */
    'projectId': number;
    /**
     * 계약명
     * @type {string}
     * @memberof ProjectContractDto
     */
    'contractName': string;
}

