/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectMilestoneTaskWorkerDto } from './project-milestone-task-worker-dto';

/**
 * 
 * @export
 * @interface ProjectMilestoneTaskListDto
 */
export interface ProjectMilestoneTaskListDto {
    /**
     * 마일스톤 ID<br>마일스톤 ID가 없는 경우 타임라인에 표시되지 않습니다.
     * @type {number}
     * @memberof ProjectMilestoneTaskListDto
     */
    'id': number;
    /**
     * 작업 제목
     * @type {string}
     * @memberof ProjectMilestoneTaskListDto
     */
    'taskName': string;
    /**
     * 예상 작업 시작일
     * @type {string}
     * @memberof ProjectMilestoneTaskListDto
     */
    'expectedStartDate'?: string;
    /**
     * 예상 작업 마감일
     * @type {string}
     * @memberof ProjectMilestoneTaskListDto
     */
    'expectedEndDate'?: string;
    /**
     * 최종 마감일
     * @type {string}
     * @memberof ProjectMilestoneTaskListDto
     */
    'finalEndDate'?: string;
    /**
     * 마지막 업데이트
     * @type {string}
     * @memberof ProjectMilestoneTaskListDto
     */
    'lastUpdateDate'?: string;
    /**
     * 담당자 목록
     * @type {Array<ProjectMilestoneTaskWorkerDto>}
     * @memberof ProjectMilestoneTaskListDto
     */
    'projectWorkerList'?: Array<ProjectMilestoneTaskWorkerDto>;
    /**
     * 진행률
     * @type {number}
     * @memberof ProjectMilestoneTaskListDto
     */
    'progressPercent'?: number;
    /**
     * 작업 상태 (NOT_STARTED: 진행 전, IN_PROGRESS: 진행 중, EDITING: 수정 중, DONE: 컨펌 완료)
     * @type {string}
     * @memberof ProjectMilestoneTaskListDto
     */
    'taskStatus'?: ProjectMilestoneTaskListDtoTaskStatusEnum;
}

export const ProjectMilestoneTaskListDtoTaskStatusEnum = {
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Editing: 'EDITING',
    Done: 'DONE'
} as const;

export type ProjectMilestoneTaskListDtoTaskStatusEnum = typeof ProjectMilestoneTaskListDtoTaskStatusEnum[keyof typeof ProjectMilestoneTaskListDtoTaskStatusEnum];


