/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 배정된 작업
 * @export
 * @interface ProjectTaskDto
 */
export interface ProjectTaskDto {
    /**
     * 작업 아이디
     * @type {number}
     * @memberof ProjectTaskDto
     */
    'id': number;
    /**
     * 작업 이름
     * @type {string}
     * @memberof ProjectTaskDto
     */
    'taskName': string;
}

