/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectRoleDto } from './project-role-dto';

/**
 * 
 * @export
 * @interface ProjectWorkerRecruitmentListDto
 */
export interface ProjectWorkerRecruitmentListDto {
    /**
     * 외주 공고 아이디
     * @type {number}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'id': number;
    /**
     * 직무
     * @type {ProjectRoleDto}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'role': ProjectRoleDto;
    /**
     * 외주 공고명
     * @type {string}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'title': string;
    /**
     * 계약 시작 날짜
     * @type {string}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'contractStartDate'?: string;
    /**
     * 계약 종료 날짜
     * @type {string}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'contractEndDate'?: string;
    /**
     * 좋아요 여부
     * @type {boolean}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'isLiked': boolean;
    /**
     * 좋아요 수
     * @type {number}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'likeCnt': number;
    /**
     * 예상 수입
     * @type {number}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'expectedWage'?: number;
    /**
     * 공고 상태 (WAIT: 대기, IN_PROGRESS: 모집중, REVIEW: 검토중, COMPLETE: 매칭완료, CANCELLED: 취소)
     * @type {string}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'recruitmentStatus': ProjectWorkerRecruitmentListDtoRecruitmentStatusEnum;
    /**
     * 지원자/참여자 수
     * @type {number}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'applyCnt': number;
    /**
     * 첫 번째 지원자 (마스킹 처리)
     * @type {string}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'firstApplicant'?: string;
    /**
     * 남은 지원자 수
     * @type {number}
     * @memberof ProjectWorkerRecruitmentListDto
     */
    'leftApplyCnt': number;
}

export const ProjectWorkerRecruitmentListDtoRecruitmentStatusEnum = {
    Wait: 'WAIT',
    InProgress: 'IN_PROGRESS',
    Reviewing: 'REVIEWING',
    Completed: 'COMPLETED',
    Cancelled: 'CANCELLED'
} as const;

export type ProjectWorkerRecruitmentListDtoRecruitmentStatusEnum = typeof ProjectWorkerRecruitmentListDtoRecruitmentStatusEnum[keyof typeof ProjectWorkerRecruitmentListDtoRecruitmentStatusEnum];


