/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectMilestoneTaskOutputDto } from './project-milestone-task-output-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { ProjectWorkerDto } from './project-worker-dto';

/**
 * 
 * @export
 * @interface ProjectMilestoneTaskDto
 */
export interface ProjectMilestoneTaskDto {
    /**
     * 프로젝트 마일스톤 테스크 아이디
     * @type {number}
     * @memberof ProjectMilestoneTaskDto
     */
    'id': number;
    /**
     * 테스크 이름
     * @type {string}
     * @memberof ProjectMilestoneTaskDto
     */
    'taskName': string;
    /**
     * 담당자
     * @type {Array<ProjectWorkerDto>}
     * @memberof ProjectMilestoneTaskDto
     */
    'projectWorkerList'?: Array<ProjectWorkerDto>;
    /**
     * 프로젝트 마일스톤 아이디
     * @type {number}
     * @memberof ProjectMilestoneTaskDto
     */
    'milestoneId': number;
    /**
     * 프로젝트 마일스톤 이름
     * @type {string}
     * @memberof ProjectMilestoneTaskDto
     */
    'milestoneName': string;
    /**
     * 진행률
     * @type {number}
     * @memberof ProjectMilestoneTaskDto
     */
    'progressPercent': number;
    /**
     * 예상 업무 시작일
     * @type {string}
     * @memberof ProjectMilestoneTaskDto
     */
    'expectedStartDate'?: string;
    /**
     * 예상 업무 마감일
     * @type {string}
     * @memberof ProjectMilestoneTaskDto
     */
    'expectedEndDate'?: string;
    /**
     * 산출물 목록
     * @type {Array<ProjectMilestoneTaskOutputDto>}
     * @memberof ProjectMilestoneTaskDto
     */
    'outputList'?: Array<ProjectMilestoneTaskOutputDto>;
}

