/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 담당자 목록
 * @export
 * @interface ProjectMilestoneTaskWorkerDto
 */
export interface ProjectMilestoneTaskWorkerDto {
    /**
     * 작업자 아이디
     * @type {number}
     * @memberof ProjectMilestoneTaskWorkerDto
     */
    'id': number;
    /**
     * 작업자 닉네임
     * @type {string}
     * @memberof ProjectMilestoneTaskWorkerDto
     */
    'nickName': string;
    /**
     * 작업자 프로필 사진 URL
     * @type {string}
     * @memberof ProjectMilestoneTaskWorkerDto
     */
    'profileImgUrl'?: string;
}

