/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ProjectWorkerDto } from './project-worker-dto';

/**
 * 
 * @export
 * @interface ProjectWorkHistoryListDto
 */
export interface ProjectWorkHistoryListDto {
    /**
     * 작업 내역 ID
     * @type {number}
     * @memberof ProjectWorkHistoryListDto
     */
    'id': number;
    /**
     * 작업 ID<br>테스크가 존재하는 경우에만 반환됩니다.
     * @type {number}
     * @memberof ProjectWorkHistoryListDto
     */
    'taskId'?: number;
    /**
     * 작업 이름<br>테스크가 존재하는 경우에만 반환됩니다.
     * @type {string}
     * @memberof ProjectWorkHistoryListDto
     */
    'taskName'?: string;
    /**
     * 상세 내용 ID
     * @type {number}
     * @memberof ProjectWorkHistoryListDto
     */
    'workDescriptionId': number;
    /**
     * 상세 내용
     * @type {string}
     * @memberof ProjectWorkHistoryListDto
     */
    'workDescription': string;
    /**
     * 프로젝트 담당자
     * @type {ProjectWorkerDto}
     * @memberof ProjectWorkHistoryListDto
     */
    'projectWorker': ProjectWorkerDto;
    /**
     * 작업 시작 시간
     * @type {string}
     * @memberof ProjectWorkHistoryListDto
     */
    'workStartAt': string;
    /**
     * 작업 마감 시간
     * @type {string}
     * @memberof ProjectWorkHistoryListDto
     */
    'workEndAt'?: string;
    /**
     * 작업 시간
     * @type {number}
     * @memberof ProjectWorkHistoryListDto
     */
    'workTime'?: number;
    /**
     * 진행률
     * @type {number}
     * @memberof ProjectWorkHistoryListDto
     */
    'progressPercent'?: number;
    /**
     * PM 컨펌 여부
     * @type {boolean}
     * @memberof ProjectWorkHistoryListDto
     */
    'isConfirmed': boolean;
}

