/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectWorkerContractCheckRequest
 */
export interface ProjectWorkerContractCheckRequest {
    /**
     * 작업자 확인 유무
     * @type {boolean}
     * @memberof ProjectWorkerContractCheckRequest
     */
    'workerChecked': boolean;
}

