/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectListDto
 */
export interface ProjectListDto {
    /**
     * 프로젝트 아이디
     * @type {number}
     * @memberof ProjectListDto
     */
    'id': number;
    /**
     * 프로젝트 작업자 아이디
     * @type {number}
     * @memberof ProjectListDto
     */
    'projectWorkerId': number;
    /**
     * 프로젝트 계약 아이디
     * @type {number}
     * @memberof ProjectListDto
     */
    'clientProjectContractId': number;
    /**
     * 관리직 여부 (true, false)
     * @type {boolean}
     * @memberof ProjectListDto
     */
    'isLeadWorker': boolean;
    /**
     * 마일스톤 존재 여부 (true, false)<br>관리직이 없으면서 마일스톤이 0개라면 마일스톤 존재가 false로 반환됩니다.
     * @type {boolean}
     * @memberof ProjectListDto
     */
    'existMilestone': boolean;
    /**
     * 직무
     * @type {string}
     * @memberof ProjectListDto
     */
    'role': string;
    /**
     * 프로젝트명
     * @type {string}
     * @memberof ProjectListDto
     */
    'title': string;
    /**
     * 매칭 완료 날짜
     * @type {string}
     * @memberof ProjectListDto
     */
    'matchedDate'?: string;
    /**
     * 프로젝트 시작 날짜
     * @type {string}
     * @memberof ProjectListDto
     */
    'expectedStartDate'?: string;
    /**
     * 프로젝트 마감 날짜
     * @type {string}
     * @memberof ProjectListDto
     */
    'expectedEndDate'?: string;
    /**
     * 프로젝트 상태 (WAIT: 대기, IN_PROGRESS: 진행 중, COMPLETE: 마감)
     * @type {string}
     * @memberof ProjectListDto
     */
    'workerStatus': ProjectListDtoWorkerStatusEnum;
    /**
     * 보고서 조회 UUID
     * @type {string}
     * @memberof ProjectListDto
     */
    'reportUuid'?: string;
}

export const ProjectListDtoWorkerStatusEnum = {
    Wait: 'WAIT',
    InProgress: 'IN_PROGRESS',
    Complete: 'COMPLETE',
    Termination: 'TERMINATION'
} as const;

export type ProjectListDtoWorkerStatusEnum = typeof ProjectListDtoWorkerStatusEnum[keyof typeof ProjectListDtoWorkerStatusEnum];


