/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectMilestoneTaskHistoryListDto
 */
export interface ProjectMilestoneTaskHistoryListDto {
    /**
     * 마일스톤 테스크 아이디
     * @type {number}
     * @memberof ProjectMilestoneTaskHistoryListDto
     */
    'id': number;
    /**
     * 상태 변경 날짜
     * @type {string}
     * @memberof ProjectMilestoneTaskHistoryListDto
     */
    'updatedDate'?: string;
    /**
     * 작업 상태 (NOT_STARTED: 진행 전, IN_PROGRESS: 진행 중, EDITING: 수정 중, DONE: 컨펌 완료)
     * @type {string}
     * @memberof ProjectMilestoneTaskHistoryListDto
     */
    'taskStatus'?: ProjectMilestoneTaskHistoryListDtoTaskStatusEnum;
}

export const ProjectMilestoneTaskHistoryListDtoTaskStatusEnum = {
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Editing: 'EDITING',
    Done: 'DONE'
} as const;

export type ProjectMilestoneTaskHistoryListDtoTaskStatusEnum = typeof ProjectMilestoneTaskHistoryListDtoTaskStatusEnum[keyof typeof ProjectMilestoneTaskHistoryListDtoTaskStatusEnum];


