/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectReportListDto
 */
export interface ProjectReportListDto {
    /**
     * 프로젝트 보고서 ID
     * @type {number}
     * @memberof ProjectReportListDto
     */
    'id': number;
    /**
     * 프로젝트 ID
     * @type {number}
     * @memberof ProjectReportListDto
     */
    'projectId': number;
    /**
     * 보고서 제목
     * @type {string}
     * @memberof ProjectReportListDto
     */
    'reportTitle': string;
    /**
     * 보고서 작성 일자
     * @type {string}
     * @memberof ProjectReportListDto
     */
    'reportWriteDate': string;
    /**
     * 보고서 URL
     * @type {string}
     * @memberof ProjectReportListDto
     */
    'reportUrl': string;
    /**
     * 의뢰자 표시 여부 (true/false)
     * @type {boolean}
     * @memberof ProjectReportListDto
     */
    'isShowingClient': boolean;
    /**
     * 프로젝트 리드 작업자에게 표시 여부 (true/false)
     * @type {boolean}
     * @memberof ProjectReportListDto
     */
    'isShowingLeadWorker': boolean;
}

