/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectWorkTimesDto
 */
export interface ProjectWorkTimesDto {
    /**
     * 프로젝트 전체 작업 시간
     * @type {number}
     * @memberof ProjectWorkTimesDto
     */
    'totalWorkTime': number;
    /**
     * 이번 달 작업 시간
     * @type {number}
     * @memberof ProjectWorkTimesDto
     */
    'monthWorkTime': number;
    /**
     * 이번 주 작업 시간
     * @type {number}
     * @memberof ProjectWorkTimesDto
     */
    'weekWorkTime': number;
    /**
     * 이번 달 예상 정산금
     * @type {number}
     * @memberof ProjectWorkTimesDto
     */
    'expectedPay': number;
}

