/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectWorkerDto
 */
export interface ProjectWorkerDto {
    /**
     * 작업자 아이디
     * @type {number}
     * @memberof ProjectWorkerDto
     */
    'id': number;
    /**
     * 작업자 이름
     * @type {string}
     * @memberof ProjectWorkerDto
     */
    'name': string;
    /**
     * 작업자 직책
     * @type {string}
     * @memberof ProjectWorkerDto
     */
    'role': string;
}

