/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectMilestoneListDto
 */
export interface ProjectMilestoneListDto {
    /**
     * 프로젝트 마일스톤 아이디
     * @type {number}
     * @memberof ProjectMilestoneListDto
     */
    'id': number;
    /**
     * 프로젝트 마일스톤 이름
     * @type {string}
     * @memberof ProjectMilestoneListDto
     */
    'milestoneName': string;
    /**
     * 프로젝트 마일스톤 달성 목표
     * @type {string}
     * @memberof ProjectMilestoneListDto
     */
    'milestoneObjective': string;
    /**
     * 프로젝트 마일스톤 상태 (NOT_STARTED: 진행 전, IN_PROGRESS: 진행 중, COMPLETE: 완료, OVERDUE: 기간 초과)
     * @type {string}
     * @memberof ProjectMilestoneListDto
     */
    'milestoneStatus': ProjectMilestoneListDtoMilestoneStatusEnum;
    /**
     * 마일스톤 시작일
     * @type {string}
     * @memberof ProjectMilestoneListDto
     */
    'milestoneStartDate': string;
    /**
     * 마일스톤 마감일
     * @type {string}
     * @memberof ProjectMilestoneListDto
     */
    'milestoneEndDate': string;
    /**
     * 마일스톤 진행률
     * @type {number}
     * @memberof ProjectMilestoneListDto
     */
    'progressPercent': number;
}

export const ProjectMilestoneListDtoMilestoneStatusEnum = {
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Complete: 'COMPLETE',
    Overdue: 'OVERDUE'
} as const;

export type ProjectMilestoneListDtoMilestoneStatusEnum = typeof ProjectMilestoneListDtoMilestoneStatusEnum[keyof typeof ProjectMilestoneListDtoMilestoneStatusEnum];


