/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectWorkHistoryProgressDto
 */
export interface ProjectWorkHistoryProgressDto {
    /**
     * 이전 작업 진행률
     * @type {number}
     * @memberof ProjectWorkHistoryProgressDto
     */
    'prevProgressPercent': number;
    /**
     * 다음 작업 진행률
     * @type {number}
     * @memberof ProjectWorkHistoryProgressDto
     */
    'nextProgressPercent': number;
}

