/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ProjectWorkHistoryDetailDto
 */
export interface ProjectWorkHistoryDetailDto {
    /**
     * 상세 내용 ID
     * @type {number}
     * @memberof ProjectWorkHistoryDetailDto
     */
    'id': number;
    /**
     * 상세 내용
     * @type {string}
     * @memberof ProjectWorkHistoryDetailDto
     */
    'workDescription': string;
    /**
     * 마지막 진행률
     * @type {number}
     * @memberof ProjectWorkHistoryDetailDto
     */
    'lastProgressPercent': number;
}

