/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PutProjectMilestoneTaskRequest
 */
export interface PutProjectMilestoneTaskRequest {
    /**
     * 테스크 이름
     * @type {string}
     * @memberof PutProjectMilestoneTaskRequest
     */
    'taskName': string;
    /**
     * 테스크 예상 시작 일자
     * @type {string}
     * @memberof PutProjectMilestoneTaskRequest
     */
    'expectedStartDate'?: string;
    /**
     * 테스크 담당 작업자 ID 목록
     * @type {Array<number>}
     * @memberof PutProjectMilestoneTaskRequest
     */
    'projectWorkerIdList'?: Array<number>;
    /**
     * 테스크 예상 종료 일자
     * @type {string}
     * @memberof PutProjectMilestoneTaskRequest
     */
    'expectedEndDate'?: string;
}

