/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobCategoryIdDto } from './job-category-id-dto';
// May contain unused imports in some cases
// @ts-ignore
import type { PortfolioFileListDto } from './portfolio-file-list-dto';

/**
 * 
 * @export
 * @interface PutUserDetailInfoRequest
 */
export interface PutUserDetailInfoRequest {
    /**
     * 60일 동안 프로젝트 제안받지 않기 여부 (true - 제안 받지 않기 활성화 /false - 제안 받지 않기 비활성화)
     * @type {boolean}
     * @memberof PutUserDetailInfoRequest
     */
    'isRecruitmentAlimTalkDeny': boolean;
    /**
     * 파일 URL
     * @type {string}
     * @memberof PutUserDetailInfoRequest
     */
    'profileImgUrl'?: string;
    /**
     * 1주일 기준 작업 가능 시간
     * @type {number}
     * @memberof PutUserDetailInfoRequest
     */
    'weeklyExpectUsageHours'?: number;
    /**
     * 인증번호
     * @type {string}
     * @memberof PutUserDetailInfoRequest
     */
    'verificationCode'?: string;
    /**
     * 은행명
     * @type {string}
     * @memberof PutUserDetailInfoRequest
     */
    'bankName'?: string;
    /**
     * 계좌 번호
     * @type {string}
     * @memberof PutUserDetailInfoRequest
     */
    'bankAccountNumber'?: string;
    /**
     * 직군/직무 아이디
     * @type {Array<JobCategoryIdDto>}
     * @memberof PutUserDetailInfoRequest
     */
    'jobCategoryList': Array<JobCategoryIdDto>;
    /**
     * 프레임워크 아이디 목록
     * @type {Array<number>}
     * @memberof PutUserDetailInfoRequest
     */
    'frameworkIdList'?: Array<number>;
    /**
     * 언어 아이디 목록
     * @type {Array<number>}
     * @memberof PutUserDetailInfoRequest
     */
    'languageIdList'?: Array<number>;
    /**
     * 포트폴리오 링크 목록
     * @type {Array<string>}
     * @memberof PutUserDetailInfoRequest
     */
    'portfolioLinkList'?: Array<string>;
    /**
     * 포트폴리오 파일 목록
     * @type {Array<PortfolioFileListDto>}
     * @memberof PutUserDetailInfoRequest
     */
    'portfolioFileList'?: Array<PortfolioFileListDto>;
    /**
     * 자기소개
     * @type {string}
     * @memberof PutUserDetailInfoRequest
     */
    'introduce'?: string;
    /**
     * 현재 진행 중인 프로젝트
     * @type {string}
     * @memberof PutUserDetailInfoRequest
     */
    'currentProjectStatus'?: string;
    /**
     * 기술스택과 유관한 프로젝트 경험
     * @type {string}
     * @memberof PutUserDetailInfoRequest
     */
    'projectExperience'?: string;
    /**
     * 스스로 생각한 자기 실력
     * @type {string}
     * @memberof PutUserDetailInfoRequest
     */
    'ownSkill'?: string;
    /**
     * 협업 경험
     * @type {string}
     * @memberof PutUserDetailInfoRequest
     */
    'coWorkingExperience'?: string;
    /**
     * 다른 플랫폼 외주 경험 여부
     * @type {string}
     * @memberof PutUserDetailInfoRequest
     */
    'outsourceWithOtherPlatform'?: string;
}

