/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 필드 변경값 응답 모델
 * @export
 * @interface RevisionFieldResponseLocalDate
 */
export interface RevisionFieldResponseLocalDate {
    /**
     * 변경 전 값
     * @type {string}
     * @memberof RevisionFieldResponseLocalDate
     */
    'previousValue'?: string;
    /**
     * 변경된 값
     * @type {string}
     * @memberof RevisionFieldResponseLocalDate
     */
    'changedValue'?: string;
}

