/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 필드 변경값 응답 모델
 * @export
 * @interface RevisionFieldResponseWorkerContractPaymentType
 */
export interface RevisionFieldResponseWorkerContractPaymentType {
    /**
     * 변경 전 값
     * @type {string}
     * @memberof RevisionFieldResponseWorkerContractPaymentType
     */
    'previousValue'?: RevisionFieldResponseWorkerContractPaymentTypePreviousValueEnum;
    /**
     * 변경된 값
     * @type {string}
     * @memberof RevisionFieldResponseWorkerContractPaymentType
     */
    'changedValue'?: RevisionFieldResponseWorkerContractPaymentTypeChangedValueEnum;
}

export const RevisionFieldResponseWorkerContractPaymentTypePreviousValueEnum = {
    Allinone: 'ALLINONE',
    Subscription: 'SUBSCRIPTION',
    MonthlySubscription: 'MONTHLY_SUBSCRIPTION'
} as const;

export type RevisionFieldResponseWorkerContractPaymentTypePreviousValueEnum = typeof RevisionFieldResponseWorkerContractPaymentTypePreviousValueEnum[keyof typeof RevisionFieldResponseWorkerContractPaymentTypePreviousValueEnum];
export const RevisionFieldResponseWorkerContractPaymentTypeChangedValueEnum = {
    Allinone: 'ALLINONE',
    Subscription: 'SUBSCRIPTION',
    MonthlySubscription: 'MONTHLY_SUBSCRIPTION'
} as const;

export type RevisionFieldResponseWorkerContractPaymentTypeChangedValueEnum = typeof RevisionFieldResponseWorkerContractPaymentTypeChangedValueEnum[keyof typeof RevisionFieldResponseWorkerContractPaymentTypeChangedValueEnum];


