/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { JobCategoryDto } from './job-category-dto';

/**
 * 
 * @export
 * @interface UserJobCategoryDto
 */
export interface UserJobCategoryDto {
    /**
     * 직군 별칭<br>OOO님 에 들어갈 부분입니다
     * @type {string}
     * @memberof UserJobCategoryDto
     */
    'alias'?: string;
    /**
     * 직군 목록<br>네모 박스에 들어갈 부분입니다 
     * @type {Array<JobCategoryDto>}
     * @memberof UserJobCategoryDto
     */
    'jobCategoryList'?: Array<JobCategoryDto>;
}

