/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { PortfolioFileListDto } from './portfolio-file-list-dto';

/**
 * 
 * @export
 * @interface UserDetailInfoDto
 */
export interface UserDetailInfoDto {
    /**
     * 유저 ID
     * @type {number}
     * @memberof UserDetailInfoDto
     */
    'id': number;
    /**
     * 1주일 기준 작업 가능 시간
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'weeklyExpectUsageHours'?: string;
    /**
     * 프로필 사진 GET Pre-signed URL
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'profileImgUrl'?: string;
    /**
     * 이름
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'name': string;
    /**
     * 닉네임
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'nickname': string;
    /**
     * 이메일
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'email': string;
    /**
     * 휴대폰 번호
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'phoneNumber': string;
    /**
     * 은행명
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'bankName'?: string;
    /**
     * 계좌 번호
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'bankAccountNumber'?: string;
    /**
     * 사용자가 선택한 프레임워크 목록
     * @type {Array<number>}
     * @memberof UserDetailInfoDto
     */
    'userFrameworkList'?: Array<number>;
    /**
     * 사용자가 선택한 언어 목록
     * @type {Array<number>}
     * @memberof UserDetailInfoDto
     */
    'userLanguageList'?: Array<number>;
    /**
     * 포트폴리오 링크 목록
     * @type {Array<string>}
     * @memberof UserDetailInfoDto
     */
    'portfolioLinkList'?: Array<string>;
    /**
     * 포트폴리오 파일 목록
     * @type {Array<PortfolioFileListDto>}
     * @memberof UserDetailInfoDto
     */
    'portfolioFileList'?: Array<PortfolioFileListDto>;
    /**
     * 자기 소개
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'introduce'?: string;
    /**
     * 현재 진행중인 프로젝트
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'currentProjectStatus'?: string;
    /**
     * 기술스택과 유관한 프로젝트 경험
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'projectExperience'?: string;
    /**
     * 스스로 생각한 자기 실력
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'ownSkill'?: string;
    /**
     * 협업 경험
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'coWorkingExperience'?: string;
    /**
     * 타 플랫폼 외주 경험
     * @type {string}
     * @memberof UserDetailInfoDto
     */
    'outsourceWithOtherPlatform'?: string;
    /**
     * 60일 동안 프로젝트 제안받지 않기 여부 (true - 제안 받지 않기 활성화 /false - 제안 받지 않기 비활성화)
     * @type {boolean}
     * @memberof UserDetailInfoDto
     */
    'isRecruitmentAlimTalkDeny': boolean;
}

