/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseBoolean } from '../model';
// @ts-ignore
import type { BaseResponseGetEmailVerifyResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetPhoneVerifyResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetSendEmailResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetSendPasswordResponse } from '../model';
// @ts-ignore
import type { BaseResponseNerdLoginResponse } from '../model';
// @ts-ignore
import type { BaseResponseNerdRenewalTokenResponse } from '../model';
// @ts-ignore
import type { BaseResponseSendPhoneVerifyResponse } from '../model';
// @ts-ignore
import type { NerdCheckPhoneVerifyRequest } from '../model';
// @ts-ignore
import type { NerdLoginRequest } from '../model';
// @ts-ignore
import type { NerdSendEmailRequest } from '../model';
// @ts-ignore
import type { NerdSendPasswordRequest } from '../model';
// @ts-ignore
import type { NerdSendPhoneVerifyRequest } from '../model';
// @ts-ignore
import type { NerdSignUpRequest } from '../model';
// @ts-ignore
import type { PatchPasswordRequest } from '../model';
/**
 * AuthApi - axios parameter creator
 * @export
 */
export const AuthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 작업자 로그인을 진행합니다.<br>Refresh Token은 Cookie (refreshToken)으로 전달됩니다.
         * @summary 작업자 로그인
         * @param {NerdLoginRequest} nerdLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (nerdLoginRequest: NerdLoginRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nerdLoginRequest' is not null or undefined
            assertParamExists('login', 'nerdLoginRequest', nerdLoginRequest)
            const localVarPath = `/app/workers/auth/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(nerdLoginRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Refresh Token을 사용하여 작업자의 AccessToken을 갱신합니다.
         * @summary 작업자 AccessToken 재발급
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renewalAccessToken: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/auth/renewal`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 아이디 찾기 알림톡 전송을 진행합니다.<br>만약 사용자를 찾을 수 없으면 알림톡이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
         * @summary 아이디 찾기 알림톡 전송 API
         * @param {NerdSendEmailRequest} nerdSendEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEmail: async (nerdSendEmailRequest: NerdSendEmailRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nerdSendEmailRequest' is not null or undefined
            assertParamExists('sendEmail', 'nerdSendEmailRequest', nerdSendEmailRequest)
            const localVarPath = `/app/workers/auth/email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(nerdSendEmailRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 비밀번호 찾기 이메일 전송을 진행합니다.<br>만약 사용자를 찾을 수 없으면 메일이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
         * @summary 비밀번호 찾기 이메일 전송 API
         * @param {NerdSendPasswordRequest} nerdSendPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendPassword: async (nerdSendPasswordRequest: NerdSendPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nerdSendPasswordRequest' is not null or undefined
            assertParamExists('sendPassword', 'nerdSendPasswordRequest', nerdSendPasswordRequest)
            const localVarPath = `/app/workers/auth/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(nerdSendPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 회원가입 과정 중 휴대폰 인증 번호 알림톡 전송을 진행합니다.
         * @summary 회원가입 휴대폰 인증 번호 알림톡 전송 API
         * @param {NerdSendPhoneVerifyRequest} nerdSendPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendSignUpPhoneVerify: async (nerdSendPhoneVerifyRequest: NerdSendPhoneVerifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nerdSendPhoneVerifyRequest' is not null or undefined
            assertParamExists('sendSignUpPhoneVerify', 'nerdSendPhoneVerifyRequest', nerdSendPhoneVerifyRequest)
            const localVarPath = `/app/workers/auth/sign-up/phone-verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(nerdSendPhoneVerifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 작업자 신규 회원가입을 진행합니다.
         * @summary 작업자 회원가입
         * @param {NerdSignUpRequest} nerdSignUpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUp: async (nerdSignUpRequest: NerdSignUpRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nerdSignUpRequest' is not null or undefined
            assertParamExists('signUp', 'nerdSignUpRequest', nerdSignUpRequest)
            const localVarPath = `/app/workers/auth/sign-up`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(nerdSignUpRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 회원가입 과정 중 휴대폰 인증 번호 확인을 진행합니다.
         * @summary 회원가입 휴대폰 인증 번호 확인 API
         * @param {NerdCheckPhoneVerifyRequest} nerdCheckPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpPhoneVerify1: async (nerdCheckPhoneVerifyRequest: NerdCheckPhoneVerifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nerdCheckPhoneVerifyRequest' is not null or undefined
            assertParamExists('signUpPhoneVerify1', 'nerdCheckPhoneVerifyRequest', nerdCheckPhoneVerifyRequest)
            const localVarPath = `/app/workers/auth/sign-up/phone-verify/check`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(nerdCheckPhoneVerifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 비밀번호를 변경합니다.
         * @summary 비밀번호 변경 API
         * @param {PatchPasswordRequest} patchPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePassword: async (patchPasswordRequest: PatchPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'patchPasswordRequest' is not null or undefined
            assertParamExists('updatePassword', 'patchPasswordRequest', patchPasswordRequest)
            const localVarPath = `/app/workers/auth/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 신규 회원가입 과정 중 이메일 중복 검사를 진행합니다.
         * @summary 회원가입 이메일 중복 검사 API
         * @param {string} email 이메일
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEmail: async (email: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'email' is not null or undefined
            assertParamExists('verifyEmail', 'email', email)
            const localVarPath = `/app/workers/auth/sign-up/email`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthApi - functional programming interface
 * @export
 */
export const AuthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthApiAxiosParamCreator(configuration)
    return {
        /**
         * 작업자 로그인을 진행합니다.<br>Refresh Token은 Cookie (refreshToken)으로 전달됩니다.
         * @summary 작업자 로그인
         * @param {NerdLoginRequest} nerdLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(nerdLoginRequest: NerdLoginRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseNerdLoginResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(nerdLoginRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Refresh Token을 사용하여 작업자의 AccessToken을 갱신합니다.
         * @summary 작업자 AccessToken 재발급
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async renewalAccessToken(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseNerdRenewalTokenResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.renewalAccessToken(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.renewalAccessToken']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 아이디 찾기 알림톡 전송을 진행합니다.<br>만약 사용자를 찾을 수 없으면 알림톡이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
         * @summary 아이디 찾기 알림톡 전송 API
         * @param {NerdSendEmailRequest} nerdSendEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendEmail(nerdSendEmailRequest: NerdSendEmailRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetSendEmailResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendEmail(nerdSendEmailRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.sendEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 비밀번호 찾기 이메일 전송을 진행합니다.<br>만약 사용자를 찾을 수 없으면 메일이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
         * @summary 비밀번호 찾기 이메일 전송 API
         * @param {NerdSendPasswordRequest} nerdSendPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendPassword(nerdSendPasswordRequest: NerdSendPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetSendPasswordResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendPassword(nerdSendPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.sendPassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 회원가입 과정 중 휴대폰 인증 번호 알림톡 전송을 진행합니다.
         * @summary 회원가입 휴대폰 인증 번호 알림톡 전송 API
         * @param {NerdSendPhoneVerifyRequest} nerdSendPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendSignUpPhoneVerify(nerdSendPhoneVerifyRequest: NerdSendPhoneVerifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseSendPhoneVerifyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendSignUpPhoneVerify(nerdSendPhoneVerifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.sendSignUpPhoneVerify']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 작업자 신규 회원가입을 진행합니다.
         * @summary 작업자 회원가입
         * @param {NerdSignUpRequest} nerdSignUpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signUp(nerdSignUpRequest: NerdSignUpRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signUp(nerdSignUpRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signUp']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 회원가입 과정 중 휴대폰 인증 번호 확인을 진행합니다.
         * @summary 회원가입 휴대폰 인증 번호 확인 API
         * @param {NerdCheckPhoneVerifyRequest} nerdCheckPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signUpPhoneVerify1(nerdCheckPhoneVerifyRequest: NerdCheckPhoneVerifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetPhoneVerifyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signUpPhoneVerify1(nerdCheckPhoneVerifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.signUpPhoneVerify1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 비밀번호를 변경합니다.
         * @summary 비밀번호 변경 API
         * @param {PatchPasswordRequest} patchPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePassword(patchPasswordRequest: PatchPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePassword(patchPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.updatePassword']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 신규 회원가입 과정 중 이메일 중복 검사를 진행합니다.
         * @summary 회원가입 이메일 중복 검사 API
         * @param {string} email 이메일
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyEmail(email: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetEmailVerifyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyEmail(email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthApi.verifyEmail']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthApi - factory interface
 * @export
 */
export const AuthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthApiFp(configuration)
    return {
        /**
         * 작업자 로그인을 진행합니다.<br>Refresh Token은 Cookie (refreshToken)으로 전달됩니다.
         * @summary 작업자 로그인
         * @param {NerdLoginRequest} nerdLoginRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(nerdLoginRequest: NerdLoginRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseNerdLoginResponse> {
            return localVarFp.login(nerdLoginRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Refresh Token을 사용하여 작업자의 AccessToken을 갱신합니다.
         * @summary 작업자 AccessToken 재발급
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        renewalAccessToken(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseNerdRenewalTokenResponse> {
            return localVarFp.renewalAccessToken(options).then((request) => request(axios, basePath));
        },
        /**
         * 아이디 찾기 알림톡 전송을 진행합니다.<br>만약 사용자를 찾을 수 없으면 알림톡이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
         * @summary 아이디 찾기 알림톡 전송 API
         * @param {NerdSendEmailRequest} nerdSendEmailRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendEmail(nerdSendEmailRequest: NerdSendEmailRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetSendEmailResponse> {
            return localVarFp.sendEmail(nerdSendEmailRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 비밀번호 찾기 이메일 전송을 진행합니다.<br>만약 사용자를 찾을 수 없으면 메일이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
         * @summary 비밀번호 찾기 이메일 전송 API
         * @param {NerdSendPasswordRequest} nerdSendPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendPassword(nerdSendPasswordRequest: NerdSendPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetSendPasswordResponse> {
            return localVarFp.sendPassword(nerdSendPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 회원가입 과정 중 휴대폰 인증 번호 알림톡 전송을 진행합니다.
         * @summary 회원가입 휴대폰 인증 번호 알림톡 전송 API
         * @param {NerdSendPhoneVerifyRequest} nerdSendPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendSignUpPhoneVerify(nerdSendPhoneVerifyRequest: NerdSendPhoneVerifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseSendPhoneVerifyResponse> {
            return localVarFp.sendSignUpPhoneVerify(nerdSendPhoneVerifyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 작업자 신규 회원가입을 진행합니다.
         * @summary 작업자 회원가입
         * @param {NerdSignUpRequest} nerdSignUpRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUp(nerdSignUpRequest: NerdSignUpRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.signUp(nerdSignUpRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 회원가입 과정 중 휴대폰 인증 번호 확인을 진행합니다.
         * @summary 회원가입 휴대폰 인증 번호 확인 API
         * @param {NerdCheckPhoneVerifyRequest} nerdCheckPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpPhoneVerify1(nerdCheckPhoneVerifyRequest: NerdCheckPhoneVerifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetPhoneVerifyResponse> {
            return localVarFp.signUpPhoneVerify1(nerdCheckPhoneVerifyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 비밀번호를 변경합니다.
         * @summary 비밀번호 변경 API
         * @param {PatchPasswordRequest} patchPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePassword(patchPasswordRequest: PatchPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updatePassword(patchPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 신규 회원가입 과정 중 이메일 중복 검사를 진행합니다.
         * @summary 회원가입 이메일 중복 검사 API
         * @param {string} email 이메일
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyEmail(email: string, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetEmailVerifyResponse> {
            return localVarFp.verifyEmail(email, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthApi - object-oriented interface
 * @export
 * @class AuthApi
 * @extends {BaseAPI}
 */
export class AuthApi extends BaseAPI {
    /**
     * 작업자 로그인을 진행합니다.<br>Refresh Token은 Cookie (refreshToken)으로 전달됩니다.
     * @summary 작업자 로그인
     * @param {NerdLoginRequest} nerdLoginRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public login(nerdLoginRequest: NerdLoginRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).login(nerdLoginRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Refresh Token을 사용하여 작업자의 AccessToken을 갱신합니다.
     * @summary 작업자 AccessToken 재발급
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public renewalAccessToken(options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).renewalAccessToken(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 아이디 찾기 알림톡 전송을 진행합니다.<br>만약 사용자를 찾을 수 없으면 알림톡이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
     * @summary 아이디 찾기 알림톡 전송 API
     * @param {NerdSendEmailRequest} nerdSendEmailRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public sendEmail(nerdSendEmailRequest: NerdSendEmailRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).sendEmail(nerdSendEmailRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 비밀번호 찾기 이메일 전송을 진행합니다.<br>만약 사용자를 찾을 수 없으면 메일이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
     * @summary 비밀번호 찾기 이메일 전송 API
     * @param {NerdSendPasswordRequest} nerdSendPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public sendPassword(nerdSendPasswordRequest: NerdSendPasswordRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).sendPassword(nerdSendPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 회원가입 과정 중 휴대폰 인증 번호 알림톡 전송을 진행합니다.
     * @summary 회원가입 휴대폰 인증 번호 알림톡 전송 API
     * @param {NerdSendPhoneVerifyRequest} nerdSendPhoneVerifyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public sendSignUpPhoneVerify(nerdSendPhoneVerifyRequest: NerdSendPhoneVerifyRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).sendSignUpPhoneVerify(nerdSendPhoneVerifyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 작업자 신규 회원가입을 진행합니다.
     * @summary 작업자 회원가입
     * @param {NerdSignUpRequest} nerdSignUpRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public signUp(nerdSignUpRequest: NerdSignUpRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signUp(nerdSignUpRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 회원가입 과정 중 휴대폰 인증 번호 확인을 진행합니다.
     * @summary 회원가입 휴대폰 인증 번호 확인 API
     * @param {NerdCheckPhoneVerifyRequest} nerdCheckPhoneVerifyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public signUpPhoneVerify1(nerdCheckPhoneVerifyRequest: NerdCheckPhoneVerifyRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).signUpPhoneVerify1(nerdCheckPhoneVerifyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 비밀번호를 변경합니다.
     * @summary 비밀번호 변경 API
     * @param {PatchPasswordRequest} patchPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public updatePassword(patchPasswordRequest: PatchPasswordRequest, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).updatePassword(patchPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 신규 회원가입 과정 중 이메일 중복 검사를 진행합니다.
     * @summary 회원가입 이메일 중복 검사 API
     * @param {string} email 이메일
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthApi
     */
    public verifyEmail(email: string, options?: RawAxiosRequestConfig) {
        return AuthApiFp(this.configuration).verifyEmail(email, options).then((request) => request(this.axios, this.basePath));
    }
}

