/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseGetFrameworkListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetJobCategoryListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetLanguageListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetRoleListResponse } from '../model';
/**
 * JobCategoryApi - axios parameter creator
 * @export
 */
export const JobCategoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 선택 가능한 프레임워크 목록을 조회합니다.
         * @summary 프레임워크 목록 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFrameworkList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/frameworks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 선택 가능한 직군 목록을 조회합니다.
         * @summary 직군 목록 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobCategoryList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/job-categories`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 선택 가능한 언어 목록을 조회합니다.
         * @summary 언어 목록 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLanguageList: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/languages`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 선택 가능한 직무 목록을 조회합니다.
         * @summary 직무 목록 조회 API
         * @param {number} [jobCategoryId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoleList: async (jobCategoryId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/roles`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (jobCategoryId !== undefined) {
                localVarQueryParameter['jobCategoryId'] = jobCategoryId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * JobCategoryApi - functional programming interface
 * @export
 */
export const JobCategoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = JobCategoryApiAxiosParamCreator(configuration)
    return {
        /**
         * 선택 가능한 프레임워크 목록을 조회합니다.
         * @summary 프레임워크 목록 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFrameworkList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetFrameworkListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFrameworkList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobCategoryApi.getFrameworkList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 선택 가능한 직군 목록을 조회합니다.
         * @summary 직군 목록 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getJobCategoryList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetJobCategoryListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getJobCategoryList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobCategoryApi.getJobCategoryList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 선택 가능한 언어 목록을 조회합니다.
         * @summary 언어 목록 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLanguageList(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetLanguageListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLanguageList(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobCategoryApi.getLanguageList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 선택 가능한 직무 목록을 조회합니다.
         * @summary 직무 목록 조회 API
         * @param {number} [jobCategoryId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoleList(jobCategoryId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetRoleListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoleList(jobCategoryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['JobCategoryApi.getRoleList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * JobCategoryApi - factory interface
 * @export
 */
export const JobCategoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = JobCategoryApiFp(configuration)
    return {
        /**
         * 선택 가능한 프레임워크 목록을 조회합니다.
         * @summary 프레임워크 목록 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFrameworkList(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetFrameworkListResponse> {
            return localVarFp.getFrameworkList(options).then((request) => request(axios, basePath));
        },
        /**
         * 선택 가능한 직군 목록을 조회합니다.
         * @summary 직군 목록 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getJobCategoryList(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetJobCategoryListResponse> {
            return localVarFp.getJobCategoryList(options).then((request) => request(axios, basePath));
        },
        /**
         * 선택 가능한 언어 목록을 조회합니다.
         * @summary 언어 목록 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLanguageList(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetLanguageListResponse> {
            return localVarFp.getLanguageList(options).then((request) => request(axios, basePath));
        },
        /**
         * 선택 가능한 직무 목록을 조회합니다.
         * @summary 직무 목록 조회 API
         * @param {number} [jobCategoryId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoleList(jobCategoryId?: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetRoleListResponse> {
            return localVarFp.getRoleList(jobCategoryId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * JobCategoryApi - object-oriented interface
 * @export
 * @class JobCategoryApi
 * @extends {BaseAPI}
 */
export class JobCategoryApi extends BaseAPI {
    /**
     * 선택 가능한 프레임워크 목록을 조회합니다.
     * @summary 프레임워크 목록 조회 API
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobCategoryApi
     */
    public getFrameworkList(options?: RawAxiosRequestConfig) {
        return JobCategoryApiFp(this.configuration).getFrameworkList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 선택 가능한 직군 목록을 조회합니다.
     * @summary 직군 목록 조회 API
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobCategoryApi
     */
    public getJobCategoryList(options?: RawAxiosRequestConfig) {
        return JobCategoryApiFp(this.configuration).getJobCategoryList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 선택 가능한 언어 목록을 조회합니다.
     * @summary 언어 목록 조회 API
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobCategoryApi
     */
    public getLanguageList(options?: RawAxiosRequestConfig) {
        return JobCategoryApiFp(this.configuration).getLanguageList(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 선택 가능한 직무 목록을 조회합니다.
     * @summary 직무 목록 조회 API
     * @param {number} [jobCategoryId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof JobCategoryApi
     */
    public getRoleList(jobCategoryId?: number, options?: RawAxiosRequestConfig) {
        return JobCategoryApiFp(this.configuration).getRoleList(jobCategoryId, options).then((request) => request(this.axios, this.basePath));
    }
}

