/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseGetProjectWorkerContractHistoryResponse } from '../model';
// @ts-ignore
import type { BaseResponseVoid } from '../model';
// @ts-ignore
import type { ProjectWorkerContractCheckRequest } from '../model';
/**
 * ProjectWorkerContractApi - axios parameter creator
 * @export
 */
export const ProjectWorkerContractApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 프로젝트 작업자 계약에 대한 계약 내역을 조회합니다
         * @summary 프로젝트 작업자 계약 내역 조회
         * @param {number} projectWorkerContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectContractWorkerHistory: async (projectWorkerContractId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectWorkerContractId' is not null or undefined
            assertParamExists('getProjectContractWorkerHistory', 'projectWorkerContractId', projectWorkerContractId)
            const localVarPath = `/app/workers/project-worker-contracts/{projectWorkerContractId}/history`
                .replace(`{${"projectWorkerContractId"}}`, encodeURIComponent(String(projectWorkerContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 작업자 계약 특약 정보를 확인 혹은 미확인 처리합니다.
         * @summary 프로젝트 작업자 계약 특약 정보 확인/미확인 처리
         * @param {number} projectWorkerContractId 
         * @param {number} contractTermId 
         * @param {ProjectWorkerContractCheckRequest} projectWorkerContractCheckRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectWorkerCost: async (projectWorkerContractId: number, contractTermId: number, projectWorkerContractCheckRequest: ProjectWorkerContractCheckRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectWorkerContractId' is not null or undefined
            assertParamExists('getProjectWorkerCost', 'projectWorkerContractId', projectWorkerContractId)
            // verify required parameter 'contractTermId' is not null or undefined
            assertParamExists('getProjectWorkerCost', 'contractTermId', contractTermId)
            // verify required parameter 'projectWorkerContractCheckRequest' is not null or undefined
            assertParamExists('getProjectWorkerCost', 'projectWorkerContractCheckRequest', projectWorkerContractCheckRequest)
            const localVarPath = `/app/workers/project-worker-contracts/{projectWorkerContractId}/terms/{contractTermId}/check`
                .replace(`{${"projectWorkerContractId"}}`, encodeURIComponent(String(projectWorkerContractId)))
                .replace(`{${"contractTermId"}}`, encodeURIComponent(String(contractTermId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(projectWorkerContractCheckRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 작업자 계약 내역을 확인 혹은 미확인 처리합니다.
         * @summary 프로젝트 작업자 계약 내역 확인/미확인 처리
         * @param {number} projectWorkerContractId 
         * @param {number} revisionId 
         * @param {ProjectWorkerContractCheckRequest} projectWorkerContractCheckRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectWorkerContractCheck: async (projectWorkerContractId: number, revisionId: number, projectWorkerContractCheckRequest: ProjectWorkerContractCheckRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectWorkerContractId' is not null or undefined
            assertParamExists('updateProjectWorkerContractCheck', 'projectWorkerContractId', projectWorkerContractId)
            // verify required parameter 'revisionId' is not null or undefined
            assertParamExists('updateProjectWorkerContractCheck', 'revisionId', revisionId)
            // verify required parameter 'projectWorkerContractCheckRequest' is not null or undefined
            assertParamExists('updateProjectWorkerContractCheck', 'projectWorkerContractCheckRequest', projectWorkerContractCheckRequest)
            const localVarPath = `/app/workers/project-worker-contracts/{projectWorkerContractId}/{revisionId}/check`
                .replace(`{${"projectWorkerContractId"}}`, encodeURIComponent(String(projectWorkerContractId)))
                .replace(`{${"revisionId"}}`, encodeURIComponent(String(revisionId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(projectWorkerContractCheckRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectWorkerContractApi - functional programming interface
 * @export
 */
export const ProjectWorkerContractApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectWorkerContractApiAxiosParamCreator(configuration)
    return {
        /**
         * 프로젝트 작업자 계약에 대한 계약 내역을 조회합니다
         * @summary 프로젝트 작업자 계약 내역 조회
         * @param {number} projectWorkerContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectContractWorkerHistory(projectWorkerContractId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkerContractHistoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectContractWorkerHistory(projectWorkerContractId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectWorkerContractApi.getProjectContractWorkerHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 작업자 계약 특약 정보를 확인 혹은 미확인 처리합니다.
         * @summary 프로젝트 작업자 계약 특약 정보 확인/미확인 처리
         * @param {number} projectWorkerContractId 
         * @param {number} contractTermId 
         * @param {ProjectWorkerContractCheckRequest} projectWorkerContractCheckRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectWorkerCost(projectWorkerContractId: number, contractTermId: number, projectWorkerContractCheckRequest: ProjectWorkerContractCheckRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectWorkerCost(projectWorkerContractId, contractTermId, projectWorkerContractCheckRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectWorkerContractApi.getProjectWorkerCost']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 작업자 계약 내역을 확인 혹은 미확인 처리합니다.
         * @summary 프로젝트 작업자 계약 내역 확인/미확인 처리
         * @param {number} projectWorkerContractId 
         * @param {number} revisionId 
         * @param {ProjectWorkerContractCheckRequest} projectWorkerContractCheckRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProjectWorkerContractCheck(projectWorkerContractId: number, revisionId: number, projectWorkerContractCheckRequest: ProjectWorkerContractCheckRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseVoid>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProjectWorkerContractCheck(projectWorkerContractId, revisionId, projectWorkerContractCheckRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectWorkerContractApi.updateProjectWorkerContractCheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProjectWorkerContractApi - factory interface
 * @export
 */
export const ProjectWorkerContractApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectWorkerContractApiFp(configuration)
    return {
        /**
         * 프로젝트 작업자 계약에 대한 계약 내역을 조회합니다
         * @summary 프로젝트 작업자 계약 내역 조회
         * @param {number} projectWorkerContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectContractWorkerHistory(projectWorkerContractId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkerContractHistoryResponse> {
            return localVarFp.getProjectContractWorkerHistory(projectWorkerContractId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 작업자 계약 특약 정보를 확인 혹은 미확인 처리합니다.
         * @summary 프로젝트 작업자 계약 특약 정보 확인/미확인 처리
         * @param {number} projectWorkerContractId 
         * @param {number} contractTermId 
         * @param {ProjectWorkerContractCheckRequest} projectWorkerContractCheckRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectWorkerCost(projectWorkerContractId: number, contractTermId: number, projectWorkerContractCheckRequest: ProjectWorkerContractCheckRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseVoid> {
            return localVarFp.getProjectWorkerCost(projectWorkerContractId, contractTermId, projectWorkerContractCheckRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 작업자 계약 내역을 확인 혹은 미확인 처리합니다.
         * @summary 프로젝트 작업자 계약 내역 확인/미확인 처리
         * @param {number} projectWorkerContractId 
         * @param {number} revisionId 
         * @param {ProjectWorkerContractCheckRequest} projectWorkerContractCheckRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectWorkerContractCheck(projectWorkerContractId: number, revisionId: number, projectWorkerContractCheckRequest: ProjectWorkerContractCheckRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseVoid> {
            return localVarFp.updateProjectWorkerContractCheck(projectWorkerContractId, revisionId, projectWorkerContractCheckRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectWorkerContractApi - object-oriented interface
 * @export
 * @class ProjectWorkerContractApi
 * @extends {BaseAPI}
 */
export class ProjectWorkerContractApi extends BaseAPI {
    /**
     * 프로젝트 작업자 계약에 대한 계약 내역을 조회합니다
     * @summary 프로젝트 작업자 계약 내역 조회
     * @param {number} projectWorkerContractId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectWorkerContractApi
     */
    public getProjectContractWorkerHistory(projectWorkerContractId: number, options?: RawAxiosRequestConfig) {
        return ProjectWorkerContractApiFp(this.configuration).getProjectContractWorkerHistory(projectWorkerContractId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 작업자 계약 특약 정보를 확인 혹은 미확인 처리합니다.
     * @summary 프로젝트 작업자 계약 특약 정보 확인/미확인 처리
     * @param {number} projectWorkerContractId 
     * @param {number} contractTermId 
     * @param {ProjectWorkerContractCheckRequest} projectWorkerContractCheckRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectWorkerContractApi
     */
    public getProjectWorkerCost(projectWorkerContractId: number, contractTermId: number, projectWorkerContractCheckRequest: ProjectWorkerContractCheckRequest, options?: RawAxiosRequestConfig) {
        return ProjectWorkerContractApiFp(this.configuration).getProjectWorkerCost(projectWorkerContractId, contractTermId, projectWorkerContractCheckRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 작업자 계약 내역을 확인 혹은 미확인 처리합니다.
     * @summary 프로젝트 작업자 계약 내역 확인/미확인 처리
     * @param {number} projectWorkerContractId 
     * @param {number} revisionId 
     * @param {ProjectWorkerContractCheckRequest} projectWorkerContractCheckRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectWorkerContractApi
     */
    public updateProjectWorkerContractCheck(projectWorkerContractId: number, revisionId: number, projectWorkerContractCheckRequest: ProjectWorkerContractCheckRequest, options?: RawAxiosRequestConfig) {
        return ProjectWorkerContractApiFp(this.configuration).updateProjectWorkerContractCheck(projectWorkerContractId, revisionId, projectWorkerContractCheckRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

