/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseBoolean } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectWorkHistoryConfirmResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectWorkHistoryDetailListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectWorkHistoryListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectWorkHistoryProgressResponse } from '../model';
// @ts-ignore
import type { BaseResponseLong } from '../model';
// @ts-ignore
import type { PatchProjectWorkHistoryRequest } from '../model';
// @ts-ignore
import type { PostProjectWorkHistoryRequest } from '../model';
/**
 * ProjectWorkerWorkHistoryApi - axios parameter creator
 * @export
 */
export const ProjectWorkerWorkHistoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 작업자의 프로젝트 작업 기록 컨펌을 진행합니다.
         * @summary 프로젝트 작업 기록 컨펌/컨펌 해제 API - PM용
         * @param {number} clientProjectContractId 
         * @param {number} workHistoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirmWorkHistory: async (clientProjectContractId: number, workHistoryId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('confirmWorkHistory', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'workHistoryId' is not null or undefined
            assertParamExists('confirmWorkHistory', 'workHistoryId', workHistoryId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/work-histories/{workHistoryId}/confirmation`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"workHistoryId"}}`, encodeURIComponent(String(workHistoryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 새로운 프로젝트 작업 기록을 등록합니다.
         * @summary 프로젝트 작업 기록 등록 API
         * @param {number} clientProjectContractId 
         * @param {PostProjectWorkHistoryRequest} postProjectWorkHistoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectWorkHistory: async (clientProjectContractId: number, postProjectWorkHistoryRequest: PostProjectWorkHistoryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('createProjectWorkHistory', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'postProjectWorkHistoryRequest' is not null or undefined
            assertParamExists('createProjectWorkHistory', 'postProjectWorkHistoryRequest', postProjectWorkHistoryRequest)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/work-histories`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postProjectWorkHistoryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기존 프로젝트 작업 기록을 삭제합니다.<br>이미 PM 컨펌이 완료된 작업 기록은 삭제할 수 없으며, 관리직이 아니라면 자신의 작업 기록만 삭제할 수 있습니다.
         * @summary 프로젝트 작업 기록 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} workHistoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectWorkHistory: async (clientProjectContractId: number, workHistoryId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('deleteProjectWorkHistory', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'workHistoryId' is not null or undefined
            assertParamExists('deleteProjectWorkHistory', 'workHistoryId', workHistoryId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/work-histories/{workHistoryId}`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"workHistoryId"}}`, encodeURIComponent(String(workHistoryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 작업 기록 목록을 조회합니다.<br>작업자, 직무, 날짜 필터는 지정된 workHistoryFilter로만 적용이 됩니다.<br>milestoneId가 없는 경우에는 마일스톤이 지정되지 않은 공통 테스크의 작업 기록을 조회합니다.
         * @summary 프로젝트 작업 기록 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {Array<number>} [roleId] 
         * @param {number} [projectWorkerId] 작업자 ID
         * @param {string} [startDate] 작업 날짜 - 시작
         * @param {string} [endDate] 작업 날짜 - 종료
         * @param {number} [milestoneId] 프로젝트 마일스톤 ID&lt;br&gt;null로 보내면 전체 작업 기록, 0으로 보내면 공통 테스크의 작업 기록이 조회됩니다.&lt;br&gt;null 혹은 0이 아닌 milestoneId를 보내면 해당 마일스톤의 작업 기록이 조회됩니다.
         * @param {number} [taskId] 프로젝트 마일스톤 테스크 ID&lt;br&gt;공통 테스크의 작업 기록을 조회하려면 milestoneId를 null 혹은 0으로 설정해야 합니다.
         * @param {string} [workHistoryFilter] 작업 내역 필터 종류 (NONE: 필터 없음, ROLE: 직무, PROJECT_WORKER: 담당자, WORK_DATE: 작업 날짜)
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectMilestoneWorkHistoryList: async (clientProjectContractId: number, roleId?: Array<number>, projectWorkerId?: number, startDate?: string, endDate?: string, milestoneId?: number, taskId?: number, workHistoryFilter?: string, page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectMilestoneWorkHistoryList', 'clientProjectContractId', clientProjectContractId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/work-histories`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (roleId) {
                localVarQueryParameter['roleId'] = roleId;
            }

            if (projectWorkerId !== undefined) {
                localVarQueryParameter['projectWorkerId'] = projectWorkerId;
            }

            if (startDate !== undefined) {
                localVarQueryParameter['startDate'] = startDate;
            }

            if (endDate !== undefined) {
                localVarQueryParameter['endDate'] = endDate;
            }

            if (milestoneId !== undefined) {
                localVarQueryParameter['milestoneId'] = milestoneId;
            }

            if (taskId !== undefined) {
                localVarQueryParameter['taskId'] = taskId;
            }

            if (workHistoryFilter !== undefined) {
                localVarQueryParameter['workHistoryFilter'] = workHistoryFilter;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기존에 작업자가 작성한 작업 기록 상세 내용 목록을 조회합니다.
         * @summary 프로젝트 작업 기록 상세 내용 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} projectWorkerId 
         * @param {number} taskId 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectWorkHistoryDetailList: async (clientProjectContractId: number, projectWorkerId: number, taskId: number, page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectWorkHistoryDetailList', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'projectWorkerId' is not null or undefined
            assertParamExists('getProjectWorkHistoryDetailList', 'projectWorkerId', projectWorkerId)
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('getProjectWorkHistoryDetailList', 'taskId', taskId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/work-histories/details`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (projectWorkerId !== undefined) {
                localVarQueryParameter['projectWorkerId'] = projectWorkerId;
            }

            if (taskId !== undefined) {
                localVarQueryParameter['taskId'] = taskId;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 작업 시작 시간 이전 작업 기록의 진행률과 이후 작업 기록의 진행률을 조회합니다.<br>만약 제외하고 싶은 작업 기록 진행률이 있다면 해당 작업 기록 ID를 보내주세요.<br>ex) 작업 기록 수정 시 해당 작업 기록의 진행률은 배제하고 전후 진행률을 고려해야 하는 경우
         * @summary 프로젝트 작업 기록 전후 진행률 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} workDescriptionId 
         * @param {string} workStartAt 
         * @param {number} [workHistoryId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectWorkHistoryProgress: async (clientProjectContractId: number, workDescriptionId: number, workStartAt: string, workHistoryId?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectWorkHistoryProgress', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'workDescriptionId' is not null or undefined
            assertParamExists('getProjectWorkHistoryProgress', 'workDescriptionId', workDescriptionId)
            // verify required parameter 'workStartAt' is not null or undefined
            assertParamExists('getProjectWorkHistoryProgress', 'workStartAt', workStartAt)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/work-histories/progress`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (workHistoryId !== undefined) {
                localVarQueryParameter['workHistoryId'] = workHistoryId;
            }

            if (workDescriptionId !== undefined) {
                localVarQueryParameter['workDescriptionId'] = workDescriptionId;
            }

            if (workStartAt !== undefined) {
                localVarQueryParameter['workStartAt'] = workStartAt;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기존 프로젝트 작업 기록을 수정합니다.<br>이미 PM 컨펌이 완료된 작업 기록은 수정할 수 없으며, PM이 아니라면 자신의 작업 기록만 수정할 수 있습니다.<br>수정하지 않은 값도 모두 보내주어야 합니다.
         * @summary 프로젝트 작업 기록 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} workHistoryId 
         * @param {PatchProjectWorkHistoryRequest} patchProjectWorkHistoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectWorkHistory: async (clientProjectContractId: number, workHistoryId: number, patchProjectWorkHistoryRequest: PatchProjectWorkHistoryRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('updateProjectWorkHistory', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'workHistoryId' is not null or undefined
            assertParamExists('updateProjectWorkHistory', 'workHistoryId', workHistoryId)
            // verify required parameter 'patchProjectWorkHistoryRequest' is not null or undefined
            assertParamExists('updateProjectWorkHistory', 'patchProjectWorkHistoryRequest', patchProjectWorkHistoryRequest)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/work-histories/{workHistoryId}`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"workHistoryId"}}`, encodeURIComponent(String(workHistoryId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchProjectWorkHistoryRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectWorkerWorkHistoryApi - functional programming interface
 * @export
 */
export const ProjectWorkerWorkHistoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectWorkerWorkHistoryApiAxiosParamCreator(configuration)
    return {
        /**
         * 작업자의 프로젝트 작업 기록 컨펌을 진행합니다.
         * @summary 프로젝트 작업 기록 컨펌/컨펌 해제 API - PM용
         * @param {number} clientProjectContractId 
         * @param {number} workHistoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async confirmWorkHistory(clientProjectContractId: number, workHistoryId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkHistoryConfirmResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.confirmWorkHistory(clientProjectContractId, workHistoryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectWorkerWorkHistoryApi.confirmWorkHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 새로운 프로젝트 작업 기록을 등록합니다.
         * @summary 프로젝트 작업 기록 등록 API
         * @param {number} clientProjectContractId 
         * @param {PostProjectWorkHistoryRequest} postProjectWorkHistoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProjectWorkHistory(clientProjectContractId: number, postProjectWorkHistoryRequest: PostProjectWorkHistoryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProjectWorkHistory(clientProjectContractId, postProjectWorkHistoryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectWorkerWorkHistoryApi.createProjectWorkHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기존 프로젝트 작업 기록을 삭제합니다.<br>이미 PM 컨펌이 완료된 작업 기록은 삭제할 수 없으며, 관리직이 아니라면 자신의 작업 기록만 삭제할 수 있습니다.
         * @summary 프로젝트 작업 기록 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} workHistoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProjectWorkHistory(clientProjectContractId: number, workHistoryId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProjectWorkHistory(clientProjectContractId, workHistoryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectWorkerWorkHistoryApi.deleteProjectWorkHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 작업 기록 목록을 조회합니다.<br>작업자, 직무, 날짜 필터는 지정된 workHistoryFilter로만 적용이 됩니다.<br>milestoneId가 없는 경우에는 마일스톤이 지정되지 않은 공통 테스크의 작업 기록을 조회합니다.
         * @summary 프로젝트 작업 기록 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {Array<number>} [roleId] 
         * @param {number} [projectWorkerId] 작업자 ID
         * @param {string} [startDate] 작업 날짜 - 시작
         * @param {string} [endDate] 작업 날짜 - 종료
         * @param {number} [milestoneId] 프로젝트 마일스톤 ID&lt;br&gt;null로 보내면 전체 작업 기록, 0으로 보내면 공통 테스크의 작업 기록이 조회됩니다.&lt;br&gt;null 혹은 0이 아닌 milestoneId를 보내면 해당 마일스톤의 작업 기록이 조회됩니다.
         * @param {number} [taskId] 프로젝트 마일스톤 테스크 ID&lt;br&gt;공통 테스크의 작업 기록을 조회하려면 milestoneId를 null 혹은 0으로 설정해야 합니다.
         * @param {string} [workHistoryFilter] 작업 내역 필터 종류 (NONE: 필터 없음, ROLE: 직무, PROJECT_WORKER: 담당자, WORK_DATE: 작업 날짜)
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectMilestoneWorkHistoryList(clientProjectContractId: number, roleId?: Array<number>, projectWorkerId?: number, startDate?: string, endDate?: string, milestoneId?: number, taskId?: number, workHistoryFilter?: string, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkHistoryListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectMilestoneWorkHistoryList(clientProjectContractId, roleId, projectWorkerId, startDate, endDate, milestoneId, taskId, workHistoryFilter, page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectWorkerWorkHistoryApi.getProjectMilestoneWorkHistoryList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기존에 작업자가 작성한 작업 기록 상세 내용 목록을 조회합니다.
         * @summary 프로젝트 작업 기록 상세 내용 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} projectWorkerId 
         * @param {number} taskId 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectWorkHistoryDetailList(clientProjectContractId: number, projectWorkerId: number, taskId: number, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkHistoryDetailListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectWorkHistoryDetailList(clientProjectContractId, projectWorkerId, taskId, page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectWorkerWorkHistoryApi.getProjectWorkHistoryDetailList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 작업 시작 시간 이전 작업 기록의 진행률과 이후 작업 기록의 진행률을 조회합니다.<br>만약 제외하고 싶은 작업 기록 진행률이 있다면 해당 작업 기록 ID를 보내주세요.<br>ex) 작업 기록 수정 시 해당 작업 기록의 진행률은 배제하고 전후 진행률을 고려해야 하는 경우
         * @summary 프로젝트 작업 기록 전후 진행률 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} workDescriptionId 
         * @param {string} workStartAt 
         * @param {number} [workHistoryId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectWorkHistoryProgress(clientProjectContractId: number, workDescriptionId: number, workStartAt: string, workHistoryId?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkHistoryProgressResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectWorkHistoryProgress(clientProjectContractId, workDescriptionId, workStartAt, workHistoryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectWorkerWorkHistoryApi.getProjectWorkHistoryProgress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기존 프로젝트 작업 기록을 수정합니다.<br>이미 PM 컨펌이 완료된 작업 기록은 수정할 수 없으며, PM이 아니라면 자신의 작업 기록만 수정할 수 있습니다.<br>수정하지 않은 값도 모두 보내주어야 합니다.
         * @summary 프로젝트 작업 기록 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} workHistoryId 
         * @param {PatchProjectWorkHistoryRequest} patchProjectWorkHistoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProjectWorkHistory(clientProjectContractId: number, workHistoryId: number, patchProjectWorkHistoryRequest: PatchProjectWorkHistoryRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProjectWorkHistory(clientProjectContractId, workHistoryId, patchProjectWorkHistoryRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectWorkerWorkHistoryApi.updateProjectWorkHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProjectWorkerWorkHistoryApi - factory interface
 * @export
 */
export const ProjectWorkerWorkHistoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectWorkerWorkHistoryApiFp(configuration)
    return {
        /**
         * 작업자의 프로젝트 작업 기록 컨펌을 진행합니다.
         * @summary 프로젝트 작업 기록 컨펌/컨펌 해제 API - PM용
         * @param {number} clientProjectContractId 
         * @param {number} workHistoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        confirmWorkHistory(clientProjectContractId: number, workHistoryId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkHistoryConfirmResponse> {
            return localVarFp.confirmWorkHistory(clientProjectContractId, workHistoryId, options).then((request) => request(axios, basePath));
        },
        /**
         * 새로운 프로젝트 작업 기록을 등록합니다.
         * @summary 프로젝트 작업 기록 등록 API
         * @param {number} clientProjectContractId 
         * @param {PostProjectWorkHistoryRequest} postProjectWorkHistoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectWorkHistory(clientProjectContractId: number, postProjectWorkHistoryRequest: PostProjectWorkHistoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseLong> {
            return localVarFp.createProjectWorkHistory(clientProjectContractId, postProjectWorkHistoryRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 기존 프로젝트 작업 기록을 삭제합니다.<br>이미 PM 컨펌이 완료된 작업 기록은 삭제할 수 없으며, 관리직이 아니라면 자신의 작업 기록만 삭제할 수 있습니다.
         * @summary 프로젝트 작업 기록 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} workHistoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectWorkHistory(clientProjectContractId: number, workHistoryId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.deleteProjectWorkHistory(clientProjectContractId, workHistoryId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 작업 기록 목록을 조회합니다.<br>작업자, 직무, 날짜 필터는 지정된 workHistoryFilter로만 적용이 됩니다.<br>milestoneId가 없는 경우에는 마일스톤이 지정되지 않은 공통 테스크의 작업 기록을 조회합니다.
         * @summary 프로젝트 작업 기록 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {Array<number>} [roleId] 
         * @param {number} [projectWorkerId] 작업자 ID
         * @param {string} [startDate] 작업 날짜 - 시작
         * @param {string} [endDate] 작업 날짜 - 종료
         * @param {number} [milestoneId] 프로젝트 마일스톤 ID&lt;br&gt;null로 보내면 전체 작업 기록, 0으로 보내면 공통 테스크의 작업 기록이 조회됩니다.&lt;br&gt;null 혹은 0이 아닌 milestoneId를 보내면 해당 마일스톤의 작업 기록이 조회됩니다.
         * @param {number} [taskId] 프로젝트 마일스톤 테스크 ID&lt;br&gt;공통 테스크의 작업 기록을 조회하려면 milestoneId를 null 혹은 0으로 설정해야 합니다.
         * @param {string} [workHistoryFilter] 작업 내역 필터 종류 (NONE: 필터 없음, ROLE: 직무, PROJECT_WORKER: 담당자, WORK_DATE: 작업 날짜)
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectMilestoneWorkHistoryList(clientProjectContractId: number, roleId?: Array<number>, projectWorkerId?: number, startDate?: string, endDate?: string, milestoneId?: number, taskId?: number, workHistoryFilter?: string, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkHistoryListResponse> {
            return localVarFp.getProjectMilestoneWorkHistoryList(clientProjectContractId, roleId, projectWorkerId, startDate, endDate, milestoneId, taskId, workHistoryFilter, page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 기존에 작업자가 작성한 작업 기록 상세 내용 목록을 조회합니다.
         * @summary 프로젝트 작업 기록 상세 내용 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} projectWorkerId 
         * @param {number} taskId 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectWorkHistoryDetailList(clientProjectContractId: number, projectWorkerId: number, taskId: number, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkHistoryDetailListResponse> {
            return localVarFp.getProjectWorkHistoryDetailList(clientProjectContractId, projectWorkerId, taskId, page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 작업 시작 시간 이전 작업 기록의 진행률과 이후 작업 기록의 진행률을 조회합니다.<br>만약 제외하고 싶은 작업 기록 진행률이 있다면 해당 작업 기록 ID를 보내주세요.<br>ex) 작업 기록 수정 시 해당 작업 기록의 진행률은 배제하고 전후 진행률을 고려해야 하는 경우
         * @summary 프로젝트 작업 기록 전후 진행률 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} workDescriptionId 
         * @param {string} workStartAt 
         * @param {number} [workHistoryId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectWorkHistoryProgress(clientProjectContractId: number, workDescriptionId: number, workStartAt: string, workHistoryId?: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkHistoryProgressResponse> {
            return localVarFp.getProjectWorkHistoryProgress(clientProjectContractId, workDescriptionId, workStartAt, workHistoryId, options).then((request) => request(axios, basePath));
        },
        /**
         * 기존 프로젝트 작업 기록을 수정합니다.<br>이미 PM 컨펌이 완료된 작업 기록은 수정할 수 없으며, PM이 아니라면 자신의 작업 기록만 수정할 수 있습니다.<br>수정하지 않은 값도 모두 보내주어야 합니다.
         * @summary 프로젝트 작업 기록 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} workHistoryId 
         * @param {PatchProjectWorkHistoryRequest} patchProjectWorkHistoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectWorkHistory(clientProjectContractId: number, workHistoryId: number, patchProjectWorkHistoryRequest: PatchProjectWorkHistoryRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updateProjectWorkHistory(clientProjectContractId, workHistoryId, patchProjectWorkHistoryRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectWorkerWorkHistoryApi - object-oriented interface
 * @export
 * @class ProjectWorkerWorkHistoryApi
 * @extends {BaseAPI}
 */
export class ProjectWorkerWorkHistoryApi extends BaseAPI {
    /**
     * 작업자의 프로젝트 작업 기록 컨펌을 진행합니다.
     * @summary 프로젝트 작업 기록 컨펌/컨펌 해제 API - PM용
     * @param {number} clientProjectContractId 
     * @param {number} workHistoryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectWorkerWorkHistoryApi
     */
    public confirmWorkHistory(clientProjectContractId: number, workHistoryId: number, options?: RawAxiosRequestConfig) {
        return ProjectWorkerWorkHistoryApiFp(this.configuration).confirmWorkHistory(clientProjectContractId, workHistoryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 새로운 프로젝트 작업 기록을 등록합니다.
     * @summary 프로젝트 작업 기록 등록 API
     * @param {number} clientProjectContractId 
     * @param {PostProjectWorkHistoryRequest} postProjectWorkHistoryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectWorkerWorkHistoryApi
     */
    public createProjectWorkHistory(clientProjectContractId: number, postProjectWorkHistoryRequest: PostProjectWorkHistoryRequest, options?: RawAxiosRequestConfig) {
        return ProjectWorkerWorkHistoryApiFp(this.configuration).createProjectWorkHistory(clientProjectContractId, postProjectWorkHistoryRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기존 프로젝트 작업 기록을 삭제합니다.<br>이미 PM 컨펌이 완료된 작업 기록은 삭제할 수 없으며, 관리직이 아니라면 자신의 작업 기록만 삭제할 수 있습니다.
     * @summary 프로젝트 작업 기록 삭제 API
     * @param {number} clientProjectContractId 
     * @param {number} workHistoryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectWorkerWorkHistoryApi
     */
    public deleteProjectWorkHistory(clientProjectContractId: number, workHistoryId: number, options?: RawAxiosRequestConfig) {
        return ProjectWorkerWorkHistoryApiFp(this.configuration).deleteProjectWorkHistory(clientProjectContractId, workHistoryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 작업 기록 목록을 조회합니다.<br>작업자, 직무, 날짜 필터는 지정된 workHistoryFilter로만 적용이 됩니다.<br>milestoneId가 없는 경우에는 마일스톤이 지정되지 않은 공통 테스크의 작업 기록을 조회합니다.
     * @summary 프로젝트 작업 기록 목록 조회 API
     * @param {number} clientProjectContractId 
     * @param {Array<number>} [roleId] 
     * @param {number} [projectWorkerId] 작업자 ID
     * @param {string} [startDate] 작업 날짜 - 시작
     * @param {string} [endDate] 작업 날짜 - 종료
     * @param {number} [milestoneId] 프로젝트 마일스톤 ID&lt;br&gt;null로 보내면 전체 작업 기록, 0으로 보내면 공통 테스크의 작업 기록이 조회됩니다.&lt;br&gt;null 혹은 0이 아닌 milestoneId를 보내면 해당 마일스톤의 작업 기록이 조회됩니다.
     * @param {number} [taskId] 프로젝트 마일스톤 테스크 ID&lt;br&gt;공통 테스크의 작업 기록을 조회하려면 milestoneId를 null 혹은 0으로 설정해야 합니다.
     * @param {string} [workHistoryFilter] 작업 내역 필터 종류 (NONE: 필터 없음, ROLE: 직무, PROJECT_WORKER: 담당자, WORK_DATE: 작업 날짜)
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectWorkerWorkHistoryApi
     */
    public getProjectMilestoneWorkHistoryList(clientProjectContractId: number, roleId?: Array<number>, projectWorkerId?: number, startDate?: string, endDate?: string, milestoneId?: number, taskId?: number, workHistoryFilter?: string, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig) {
        return ProjectWorkerWorkHistoryApiFp(this.configuration).getProjectMilestoneWorkHistoryList(clientProjectContractId, roleId, projectWorkerId, startDate, endDate, milestoneId, taskId, workHistoryFilter, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기존에 작업자가 작성한 작업 기록 상세 내용 목록을 조회합니다.
     * @summary 프로젝트 작업 기록 상세 내용 목록 조회 API
     * @param {number} clientProjectContractId 
     * @param {number} projectWorkerId 
     * @param {number} taskId 
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectWorkerWorkHistoryApi
     */
    public getProjectWorkHistoryDetailList(clientProjectContractId: number, projectWorkerId: number, taskId: number, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig) {
        return ProjectWorkerWorkHistoryApiFp(this.configuration).getProjectWorkHistoryDetailList(clientProjectContractId, projectWorkerId, taskId, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 작업 시작 시간 이전 작업 기록의 진행률과 이후 작업 기록의 진행률을 조회합니다.<br>만약 제외하고 싶은 작업 기록 진행률이 있다면 해당 작업 기록 ID를 보내주세요.<br>ex) 작업 기록 수정 시 해당 작업 기록의 진행률은 배제하고 전후 진행률을 고려해야 하는 경우
     * @summary 프로젝트 작업 기록 전후 진행률 조회 API
     * @param {number} clientProjectContractId 
     * @param {number} workDescriptionId 
     * @param {string} workStartAt 
     * @param {number} [workHistoryId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectWorkerWorkHistoryApi
     */
    public getProjectWorkHistoryProgress(clientProjectContractId: number, workDescriptionId: number, workStartAt: string, workHistoryId?: number, options?: RawAxiosRequestConfig) {
        return ProjectWorkerWorkHistoryApiFp(this.configuration).getProjectWorkHistoryProgress(clientProjectContractId, workDescriptionId, workStartAt, workHistoryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기존 프로젝트 작업 기록을 수정합니다.<br>이미 PM 컨펌이 완료된 작업 기록은 수정할 수 없으며, PM이 아니라면 자신의 작업 기록만 수정할 수 있습니다.<br>수정하지 않은 값도 모두 보내주어야 합니다.
     * @summary 프로젝트 작업 기록 수정 API
     * @param {number} clientProjectContractId 
     * @param {number} workHistoryId 
     * @param {PatchProjectWorkHistoryRequest} patchProjectWorkHistoryRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectWorkerWorkHistoryApi
     */
    public updateProjectWorkHistory(clientProjectContractId: number, workHistoryId: number, patchProjectWorkHistoryRequest: PatchProjectWorkHistoryRequest, options?: RawAxiosRequestConfig) {
        return ProjectWorkerWorkHistoryApiFp(this.configuration).updateProjectWorkHistory(clientProjectContractId, workHistoryId, patchProjectWorkHistoryRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

