/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseBoolean } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectMilestoneListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectMilestoneProgressPercentResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectMilestoneResponse } from '../model';
// @ts-ignore
import type { BaseResponseLong } from '../model';
// @ts-ignore
import type { PatchProjectMilestoneRequest } from '../model';
// @ts-ignore
import type { PostProjectMilestoneRequest } from '../model';
/**
 * ProjectMilestoneApi - axios parameter creator
 * @export
 */
export const ProjectMilestoneApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 프로젝트 마일스톤을 생성합니다.
         * @summary 프로젝트 마일스톤 생성 API
         * @param {number} clientProjectContractId 
         * @param {PostProjectMilestoneRequest} postProjectMilestoneRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectMilestone: async (clientProjectContractId: number, postProjectMilestoneRequest: PostProjectMilestoneRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('createProjectMilestone', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'postProjectMilestoneRequest' is not null or undefined
            assertParamExists('createProjectMilestone', 'postProjectMilestoneRequest', postProjectMilestoneRequest)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postProjectMilestoneRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기존 프로젝트 마일스톤을 삭제합니다.<br>이미 하위 테스크가 만들어져 있고 작업 기록이 존재하는 경우 마일스톤은 삭제가 불가능합니다.
         * @summary 프로젝트 마일스톤 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectMilestone: async (clientProjectContractId: number, milestoneId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('deleteProjectMilestone', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('deleteProjectMilestone', 'milestoneId', milestoneId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 마일스톤 상세 정보를 조회합니다.
         * @summary 프로젝트 마일스톤 상세 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectMilestone: async (clientProjectContractId: number, milestoneId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectMilestone', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('getProjectMilestone', 'milestoneId', milestoneId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 마일스톤의 진행률을 조회합니다.
         * @summary 프로젝트 마일스톤 진행률 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectMilestoneProgressPercent: async (clientProjectContractId: number, milestoneId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectMilestoneProgressPercent', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('getProjectMilestoneProgressPercent', 'milestoneId', milestoneId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}/progress-percent`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트에 생성된 마일스톤 목록을 조회합니다.
         * @summary 프로젝트 마일스톤 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectMilestones: async (clientProjectContractId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectMilestones', 'clientProjectContractId', clientProjectContractId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 마일스톤을 수정합니다.<br>변경되지 않은 기존 값도 모두 보내주어야 합니다.
         * @summary 프로젝트 마일스톤 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {PatchProjectMilestoneRequest} patchProjectMilestoneRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectMilestone: async (clientProjectContractId: number, milestoneId: number, patchProjectMilestoneRequest: PatchProjectMilestoneRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('updateProjectMilestone', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('updateProjectMilestone', 'milestoneId', milestoneId)
            // verify required parameter 'patchProjectMilestoneRequest' is not null or undefined
            assertParamExists('updateProjectMilestone', 'patchProjectMilestoneRequest', patchProjectMilestoneRequest)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchProjectMilestoneRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectMilestoneApi - functional programming interface
 * @export
 */
export const ProjectMilestoneApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectMilestoneApiAxiosParamCreator(configuration)
    return {
        /**
         * 프로젝트 마일스톤을 생성합니다.
         * @summary 프로젝트 마일스톤 생성 API
         * @param {number} clientProjectContractId 
         * @param {PostProjectMilestoneRequest} postProjectMilestoneRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProjectMilestone(clientProjectContractId: number, postProjectMilestoneRequest: PostProjectMilestoneRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProjectMilestone(clientProjectContractId, postProjectMilestoneRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneApi.createProjectMilestone']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기존 프로젝트 마일스톤을 삭제합니다.<br>이미 하위 테스크가 만들어져 있고 작업 기록이 존재하는 경우 마일스톤은 삭제가 불가능합니다.
         * @summary 프로젝트 마일스톤 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProjectMilestone(clientProjectContractId: number, milestoneId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProjectMilestone(clientProjectContractId, milestoneId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneApi.deleteProjectMilestone']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 마일스톤 상세 정보를 조회합니다.
         * @summary 프로젝트 마일스톤 상세 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectMilestone(clientProjectContractId: number, milestoneId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectMilestoneResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectMilestone(clientProjectContractId, milestoneId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneApi.getProjectMilestone']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 마일스톤의 진행률을 조회합니다.
         * @summary 프로젝트 마일스톤 진행률 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectMilestoneProgressPercent(clientProjectContractId: number, milestoneId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectMilestoneProgressPercentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectMilestoneProgressPercent(clientProjectContractId, milestoneId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneApi.getProjectMilestoneProgressPercent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트에 생성된 마일스톤 목록을 조회합니다.
         * @summary 프로젝트 마일스톤 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectMilestones(clientProjectContractId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectMilestoneListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectMilestones(clientProjectContractId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneApi.getProjectMilestones']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 마일스톤을 수정합니다.<br>변경되지 않은 기존 값도 모두 보내주어야 합니다.
         * @summary 프로젝트 마일스톤 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {PatchProjectMilestoneRequest} patchProjectMilestoneRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProjectMilestone(clientProjectContractId: number, milestoneId: number, patchProjectMilestoneRequest: PatchProjectMilestoneRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProjectMilestone(clientProjectContractId, milestoneId, patchProjectMilestoneRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneApi.updateProjectMilestone']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProjectMilestoneApi - factory interface
 * @export
 */
export const ProjectMilestoneApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectMilestoneApiFp(configuration)
    return {
        /**
         * 프로젝트 마일스톤을 생성합니다.
         * @summary 프로젝트 마일스톤 생성 API
         * @param {number} clientProjectContractId 
         * @param {PostProjectMilestoneRequest} postProjectMilestoneRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectMilestone(clientProjectContractId: number, postProjectMilestoneRequest: PostProjectMilestoneRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseLong> {
            return localVarFp.createProjectMilestone(clientProjectContractId, postProjectMilestoneRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 기존 프로젝트 마일스톤을 삭제합니다.<br>이미 하위 테스크가 만들어져 있고 작업 기록이 존재하는 경우 마일스톤은 삭제가 불가능합니다.
         * @summary 프로젝트 마일스톤 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectMilestone(clientProjectContractId: number, milestoneId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.deleteProjectMilestone(clientProjectContractId, milestoneId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 마일스톤 상세 정보를 조회합니다.
         * @summary 프로젝트 마일스톤 상세 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectMilestone(clientProjectContractId: number, milestoneId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectMilestoneResponse> {
            return localVarFp.getProjectMilestone(clientProjectContractId, milestoneId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 마일스톤의 진행률을 조회합니다.
         * @summary 프로젝트 마일스톤 진행률 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectMilestoneProgressPercent(clientProjectContractId: number, milestoneId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectMilestoneProgressPercentResponse> {
            return localVarFp.getProjectMilestoneProgressPercent(clientProjectContractId, milestoneId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트에 생성된 마일스톤 목록을 조회합니다.
         * @summary 프로젝트 마일스톤 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectMilestones(clientProjectContractId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectMilestoneListResponse> {
            return localVarFp.getProjectMilestones(clientProjectContractId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 마일스톤을 수정합니다.<br>변경되지 않은 기존 값도 모두 보내주어야 합니다.
         * @summary 프로젝트 마일스톤 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {PatchProjectMilestoneRequest} patchProjectMilestoneRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectMilestone(clientProjectContractId: number, milestoneId: number, patchProjectMilestoneRequest: PatchProjectMilestoneRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updateProjectMilestone(clientProjectContractId, milestoneId, patchProjectMilestoneRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectMilestoneApi - object-oriented interface
 * @export
 * @class ProjectMilestoneApi
 * @extends {BaseAPI}
 */
export class ProjectMilestoneApi extends BaseAPI {
    /**
     * 프로젝트 마일스톤을 생성합니다.
     * @summary 프로젝트 마일스톤 생성 API
     * @param {number} clientProjectContractId 
     * @param {PostProjectMilestoneRequest} postProjectMilestoneRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneApi
     */
    public createProjectMilestone(clientProjectContractId: number, postProjectMilestoneRequest: PostProjectMilestoneRequest, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneApiFp(this.configuration).createProjectMilestone(clientProjectContractId, postProjectMilestoneRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기존 프로젝트 마일스톤을 삭제합니다.<br>이미 하위 테스크가 만들어져 있고 작업 기록이 존재하는 경우 마일스톤은 삭제가 불가능합니다.
     * @summary 프로젝트 마일스톤 삭제 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneApi
     */
    public deleteProjectMilestone(clientProjectContractId: number, milestoneId: number, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneApiFp(this.configuration).deleteProjectMilestone(clientProjectContractId, milestoneId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 마일스톤 상세 정보를 조회합니다.
     * @summary 프로젝트 마일스톤 상세 조회 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneApi
     */
    public getProjectMilestone(clientProjectContractId: number, milestoneId: number, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneApiFp(this.configuration).getProjectMilestone(clientProjectContractId, milestoneId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 마일스톤의 진행률을 조회합니다.
     * @summary 프로젝트 마일스톤 진행률 조회 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneApi
     */
    public getProjectMilestoneProgressPercent(clientProjectContractId: number, milestoneId: number, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneApiFp(this.configuration).getProjectMilestoneProgressPercent(clientProjectContractId, milestoneId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트에 생성된 마일스톤 목록을 조회합니다.
     * @summary 프로젝트 마일스톤 목록 조회 API
     * @param {number} clientProjectContractId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneApi
     */
    public getProjectMilestones(clientProjectContractId: number, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneApiFp(this.configuration).getProjectMilestones(clientProjectContractId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 마일스톤을 수정합니다.<br>변경되지 않은 기존 값도 모두 보내주어야 합니다.
     * @summary 프로젝트 마일스톤 수정 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {PatchProjectMilestoneRequest} patchProjectMilestoneRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneApi
     */
    public updateProjectMilestone(clientProjectContractId: number, milestoneId: number, patchProjectMilestoneRequest: PatchProjectMilestoneRequest, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneApiFp(this.configuration).updateProjectMilestone(clientProjectContractId, milestoneId, patchProjectMilestoneRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

