/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseBoolean } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectMilestoneTaskHistoryListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectMilestoneTaskListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectMilestoneTaskResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectTaskProgressPercentResponse } from '../model';
// @ts-ignore
import type { BaseResponseLong } from '../model';
// @ts-ignore
import type { BaseResponsePostProjectMilestoneTaskOutputResponse } from '../model';
// @ts-ignore
import type { PatchProjectMilestoneTaskOutputRequest } from '../model';
// @ts-ignore
import type { PatchProjectMilestoneTaskStatusRequest } from '../model';
// @ts-ignore
import type { PostProjectMilestoneTaskOutputRequest } from '../model';
// @ts-ignore
import type { PostProjectMilestoneTaskRequest } from '../model';
// @ts-ignore
import type { PutProjectMilestoneTaskRequest } from '../model';
/**
 * ProjectMilestoneTaskApi - axios parameter creator
 * @export
 */
export const ProjectMilestoneTaskApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 프로젝트 마일스톤 테스크의 새로운 산출물을 등록합니다.
         * @summary 프로젝트 마일스톤 테스크 산출물 등록 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {PostProjectMilestoneTaskOutputRequest} postProjectMilestoneTaskOutputRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectMilestoneTaskOutput: async (clientProjectContractId: number, milestoneId: number, taskId: number, postProjectMilestoneTaskOutputRequest: PostProjectMilestoneTaskOutputRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('createProjectMilestoneTaskOutput', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('createProjectMilestoneTaskOutput', 'milestoneId', milestoneId)
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('createProjectMilestoneTaskOutput', 'taskId', taskId)
            // verify required parameter 'postProjectMilestoneTaskOutputRequest' is not null or undefined
            assertParamExists('createProjectMilestoneTaskOutput', 'postProjectMilestoneTaskOutputRequest', postProjectMilestoneTaskOutputRequest)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}/tasks/{taskId}/outputs`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)))
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postProjectMilestoneTaskOutputRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 새로운 프로젝트 테스크를 생성합니다.
         * @summary 프로젝트 테스크 생성 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {PostProjectMilestoneTaskRequest} postProjectMilestoneTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectTask: async (clientProjectContractId: number, milestoneId: number, postProjectMilestoneTaskRequest: PostProjectMilestoneTaskRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('createProjectTask', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('createProjectTask', 'milestoneId', milestoneId)
            // verify required parameter 'postProjectMilestoneTaskRequest' is not null or undefined
            assertParamExists('createProjectTask', 'postProjectMilestoneTaskRequest', postProjectMilestoneTaskRequest)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}/tasks`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postProjectMilestoneTaskRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 기존 프로젝트 마일스톤 테스크를 삭제합니다.<br>이미 하위 작업 기록이 만들어져 있는 테스크는 삭제가 불가능합니다.
         * @summary 프로젝트 마일스톤 테스크 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectMilestoneTask: async (clientProjectContractId: number, milestoneId: number, taskId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('deleteProjectMilestoneTask', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('deleteProjectMilestoneTask', 'milestoneId', milestoneId)
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('deleteProjectMilestoneTask', 'taskId', taskId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}/tasks/{taskId}`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)))
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 마일스톤 테스크의 산출물을 삭제합니다.
         * @summary 프로젝트 마일스톤 테스크 산출물 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {number} outputId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectMilestoneTaskOutput: async (clientProjectContractId: number, milestoneId: number, taskId: number, outputId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('deleteProjectMilestoneTaskOutput', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('deleteProjectMilestoneTaskOutput', 'milestoneId', milestoneId)
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('deleteProjectMilestoneTaskOutput', 'taskId', taskId)
            // verify required parameter 'outputId' is not null or undefined
            assertParamExists('deleteProjectMilestoneTaskOutput', 'outputId', outputId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}/tasks/{taskId}/outputs/{outputId}`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)))
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)))
                .replace(`{${"outputId"}}`, encodeURIComponent(String(outputId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 태스크 목록을 조회합니다.<br>milestoneId를 입력한 경우에는 마일스톤 하위에 생성된 테스크와 공통 테스크를 조회하고, milestoneId를 입력하지 않은 경우에는 마일스톤이 없는 공통 테스크만 조회합니다.<br>detail이 true인 경우 작업 상세 조회를 진행합니다.
         * @summary 프로젝트 테스크 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {boolean} detail 
         * @param {number} [milestoneId] 
         * @param {number} [projectWorkerId] 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectMilestoneTasks: async (clientProjectContractId: number, detail: boolean, milestoneId?: number, projectWorkerId?: number, page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectMilestoneTasks', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'detail' is not null or undefined
            assertParamExists('getProjectMilestoneTasks', 'detail', detail)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/tasks`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (milestoneId !== undefined) {
                localVarQueryParameter['milestoneId'] = milestoneId;
            }

            if (projectWorkerId !== undefined) {
                localVarQueryParameter['projectWorkerId'] = projectWorkerId;
            }

            if (detail !== undefined) {
                localVarQueryParameter['detail'] = detail;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 테스크 상세 조회를 진행합니다.
         * @summary 프로젝트 테스크 상세 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectTask: async (clientProjectContractId: number, taskId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectTask', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('getProjectTask', 'taskId', taskId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/tasks/{taskId}`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 테스크의 히스토리 조회를 진행합니다.
         * @summary 프로젝트 마일스톤 테스크 히스토리 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectTaskHistory: async (clientProjectContractId: number, milestoneId: number, taskId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectTaskHistory', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('getProjectTaskHistory', 'milestoneId', milestoneId)
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('getProjectTaskHistory', 'taskId', taskId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}/tasks/{taskId}/histories`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)))
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 테스크 진행률 조회를 진행합니다.
         * @summary 프로젝트 테스크 진행률 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectTaskProgressPercent: async (clientProjectContractId: number, taskId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectTaskProgressPercent', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('getProjectTaskProgressPercent', 'taskId', taskId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/tasks/{taskId}/progress-percent`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 마일스톤 테스크의 산출물을 수정합니다.<br>수정을 원하는 값만 입력하고, 수정을 원하지 않는 값은 null로 보내주세요.
         * @summary 프로젝트 마일스톤 테스크 산출물 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {number} outputId 
         * @param {PatchProjectMilestoneTaskOutputRequest} patchProjectMilestoneTaskOutputRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectMilestoneTaskOutput: async (clientProjectContractId: number, milestoneId: number, taskId: number, outputId: number, patchProjectMilestoneTaskOutputRequest: PatchProjectMilestoneTaskOutputRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('updateProjectMilestoneTaskOutput', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('updateProjectMilestoneTaskOutput', 'milestoneId', milestoneId)
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('updateProjectMilestoneTaskOutput', 'taskId', taskId)
            // verify required parameter 'outputId' is not null or undefined
            assertParamExists('updateProjectMilestoneTaskOutput', 'outputId', outputId)
            // verify required parameter 'patchProjectMilestoneTaskOutputRequest' is not null or undefined
            assertParamExists('updateProjectMilestoneTaskOutput', 'patchProjectMilestoneTaskOutputRequest', patchProjectMilestoneTaskOutputRequest)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}/tasks/{taskId}/outputs/{outputId}`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)))
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)))
                .replace(`{${"outputId"}}`, encodeURIComponent(String(outputId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchProjectMilestoneTaskOutputRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 테스크를 수정합니다.<br>변경되지 않은 기존 값도 모두 보내주어야 합니다.
         * @summary 프로젝트 마일스톤 테스크 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {PutProjectMilestoneTaskRequest} putProjectMilestoneTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectTask: async (clientProjectContractId: number, milestoneId: number, taskId: number, putProjectMilestoneTaskRequest: PutProjectMilestoneTaskRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('updateProjectTask', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('updateProjectTask', 'milestoneId', milestoneId)
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('updateProjectTask', 'taskId', taskId)
            // verify required parameter 'putProjectMilestoneTaskRequest' is not null or undefined
            assertParamExists('updateProjectTask', 'putProjectMilestoneTaskRequest', putProjectMilestoneTaskRequest)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}/tasks/{taskId}`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)))
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putProjectMilestoneTaskRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 테스크의 상태를 변경합니다.
         * @summary 프로젝트 마일스톤 테스크 상태 변경 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {PatchProjectMilestoneTaskStatusRequest} patchProjectMilestoneTaskStatusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectTaskStatus: async (clientProjectContractId: number, milestoneId: number, taskId: number, patchProjectMilestoneTaskStatusRequest: PatchProjectMilestoneTaskStatusRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('updateProjectTaskStatus', 'clientProjectContractId', clientProjectContractId)
            // verify required parameter 'milestoneId' is not null or undefined
            assertParamExists('updateProjectTaskStatus', 'milestoneId', milestoneId)
            // verify required parameter 'taskId' is not null or undefined
            assertParamExists('updateProjectTaskStatus', 'taskId', taskId)
            // verify required parameter 'patchProjectMilestoneTaskStatusRequest' is not null or undefined
            assertParamExists('updateProjectTaskStatus', 'patchProjectMilestoneTaskStatusRequest', patchProjectMilestoneTaskStatusRequest)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/milestones/{milestoneId}/tasks/{taskId}/status`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)))
                .replace(`{${"milestoneId"}}`, encodeURIComponent(String(milestoneId)))
                .replace(`{${"taskId"}}`, encodeURIComponent(String(taskId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchProjectMilestoneTaskStatusRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectMilestoneTaskApi - functional programming interface
 * @export
 */
export const ProjectMilestoneTaskApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectMilestoneTaskApiAxiosParamCreator(configuration)
    return {
        /**
         * 프로젝트 마일스톤 테스크의 새로운 산출물을 등록합니다.
         * @summary 프로젝트 마일스톤 테스크 산출물 등록 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {PostProjectMilestoneTaskOutputRequest} postProjectMilestoneTaskOutputRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProjectMilestoneTaskOutput(clientProjectContractId: number, milestoneId: number, taskId: number, postProjectMilestoneTaskOutputRequest: PostProjectMilestoneTaskOutputRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePostProjectMilestoneTaskOutputResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProjectMilestoneTaskOutput(clientProjectContractId, milestoneId, taskId, postProjectMilestoneTaskOutputRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.createProjectMilestoneTaskOutput']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 새로운 프로젝트 테스크를 생성합니다.
         * @summary 프로젝트 테스크 생성 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {PostProjectMilestoneTaskRequest} postProjectMilestoneTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createProjectTask(clientProjectContractId: number, milestoneId: number, postProjectMilestoneTaskRequest: PostProjectMilestoneTaskRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseLong>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createProjectTask(clientProjectContractId, milestoneId, postProjectMilestoneTaskRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.createProjectTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 기존 프로젝트 마일스톤 테스크를 삭제합니다.<br>이미 하위 작업 기록이 만들어져 있는 테스크는 삭제가 불가능합니다.
         * @summary 프로젝트 마일스톤 테스크 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProjectMilestoneTask(clientProjectContractId: number, milestoneId: number, taskId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProjectMilestoneTask(clientProjectContractId, milestoneId, taskId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.deleteProjectMilestoneTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 마일스톤 테스크의 산출물을 삭제합니다.
         * @summary 프로젝트 마일스톤 테스크 산출물 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {number} outputId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteProjectMilestoneTaskOutput(clientProjectContractId: number, milestoneId: number, taskId: number, outputId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteProjectMilestoneTaskOutput(clientProjectContractId, milestoneId, taskId, outputId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.deleteProjectMilestoneTaskOutput']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 태스크 목록을 조회합니다.<br>milestoneId를 입력한 경우에는 마일스톤 하위에 생성된 테스크와 공통 테스크를 조회하고, milestoneId를 입력하지 않은 경우에는 마일스톤이 없는 공통 테스크만 조회합니다.<br>detail이 true인 경우 작업 상세 조회를 진행합니다.
         * @summary 프로젝트 테스크 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {boolean} detail 
         * @param {number} [milestoneId] 
         * @param {number} [projectWorkerId] 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectMilestoneTasks(clientProjectContractId: number, detail: boolean, milestoneId?: number, projectWorkerId?: number, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectMilestoneTaskListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectMilestoneTasks(clientProjectContractId, detail, milestoneId, projectWorkerId, page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.getProjectMilestoneTasks']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 테스크 상세 조회를 진행합니다.
         * @summary 프로젝트 테스크 상세 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectTask(clientProjectContractId: number, taskId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectMilestoneTaskResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectTask(clientProjectContractId, taskId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.getProjectTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 테스크의 히스토리 조회를 진행합니다.
         * @summary 프로젝트 마일스톤 테스크 히스토리 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectTaskHistory(clientProjectContractId: number, milestoneId: number, taskId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectMilestoneTaskHistoryListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectTaskHistory(clientProjectContractId, milestoneId, taskId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.getProjectTaskHistory']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 테스크 진행률 조회를 진행합니다.
         * @summary 프로젝트 테스크 진행률 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectTaskProgressPercent(clientProjectContractId: number, taskId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectTaskProgressPercentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectTaskProgressPercent(clientProjectContractId, taskId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.getProjectTaskProgressPercent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 마일스톤 테스크의 산출물을 수정합니다.<br>수정을 원하는 값만 입력하고, 수정을 원하지 않는 값은 null로 보내주세요.
         * @summary 프로젝트 마일스톤 테스크 산출물 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {number} outputId 
         * @param {PatchProjectMilestoneTaskOutputRequest} patchProjectMilestoneTaskOutputRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProjectMilestoneTaskOutput(clientProjectContractId: number, milestoneId: number, taskId: number, outputId: number, patchProjectMilestoneTaskOutputRequest: PatchProjectMilestoneTaskOutputRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProjectMilestoneTaskOutput(clientProjectContractId, milestoneId, taskId, outputId, patchProjectMilestoneTaskOutputRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.updateProjectMilestoneTaskOutput']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 테스크를 수정합니다.<br>변경되지 않은 기존 값도 모두 보내주어야 합니다.
         * @summary 프로젝트 마일스톤 테스크 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {PutProjectMilestoneTaskRequest} putProjectMilestoneTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProjectTask(clientProjectContractId: number, milestoneId: number, taskId: number, putProjectMilestoneTaskRequest: PutProjectMilestoneTaskRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProjectTask(clientProjectContractId, milestoneId, taskId, putProjectMilestoneTaskRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.updateProjectTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 테스크의 상태를 변경합니다.
         * @summary 프로젝트 마일스톤 테스크 상태 변경 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {PatchProjectMilestoneTaskStatusRequest} patchProjectMilestoneTaskStatusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateProjectTaskStatus(clientProjectContractId: number, milestoneId: number, taskId: number, patchProjectMilestoneTaskStatusRequest: PatchProjectMilestoneTaskStatusRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateProjectTaskStatus(clientProjectContractId, milestoneId, taskId, patchProjectMilestoneTaskStatusRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectMilestoneTaskApi.updateProjectTaskStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProjectMilestoneTaskApi - factory interface
 * @export
 */
export const ProjectMilestoneTaskApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectMilestoneTaskApiFp(configuration)
    return {
        /**
         * 프로젝트 마일스톤 테스크의 새로운 산출물을 등록합니다.
         * @summary 프로젝트 마일스톤 테스크 산출물 등록 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {PostProjectMilestoneTaskOutputRequest} postProjectMilestoneTaskOutputRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectMilestoneTaskOutput(clientProjectContractId: number, milestoneId: number, taskId: number, postProjectMilestoneTaskOutputRequest: PostProjectMilestoneTaskOutputRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePostProjectMilestoneTaskOutputResponse> {
            return localVarFp.createProjectMilestoneTaskOutput(clientProjectContractId, milestoneId, taskId, postProjectMilestoneTaskOutputRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 새로운 프로젝트 테스크를 생성합니다.
         * @summary 프로젝트 테스크 생성 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {PostProjectMilestoneTaskRequest} postProjectMilestoneTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createProjectTask(clientProjectContractId: number, milestoneId: number, postProjectMilestoneTaskRequest: PostProjectMilestoneTaskRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseLong> {
            return localVarFp.createProjectTask(clientProjectContractId, milestoneId, postProjectMilestoneTaskRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 기존 프로젝트 마일스톤 테스크를 삭제합니다.<br>이미 하위 작업 기록이 만들어져 있는 테스크는 삭제가 불가능합니다.
         * @summary 프로젝트 마일스톤 테스크 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectMilestoneTask(clientProjectContractId: number, milestoneId: number, taskId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.deleteProjectMilestoneTask(clientProjectContractId, milestoneId, taskId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 마일스톤 테스크의 산출물을 삭제합니다.
         * @summary 프로젝트 마일스톤 테스크 산출물 삭제 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {number} outputId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteProjectMilestoneTaskOutput(clientProjectContractId: number, milestoneId: number, taskId: number, outputId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.deleteProjectMilestoneTaskOutput(clientProjectContractId, milestoneId, taskId, outputId, options).then((request) => request(axios, basePath));
        },
        /**
         * 태스크 목록을 조회합니다.<br>milestoneId를 입력한 경우에는 마일스톤 하위에 생성된 테스크와 공통 테스크를 조회하고, milestoneId를 입력하지 않은 경우에는 마일스톤이 없는 공통 테스크만 조회합니다.<br>detail이 true인 경우 작업 상세 조회를 진행합니다.
         * @summary 프로젝트 테스크 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {boolean} detail 
         * @param {number} [milestoneId] 
         * @param {number} [projectWorkerId] 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectMilestoneTasks(clientProjectContractId: number, detail: boolean, milestoneId?: number, projectWorkerId?: number, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectMilestoneTaskListResponse> {
            return localVarFp.getProjectMilestoneTasks(clientProjectContractId, detail, milestoneId, projectWorkerId, page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 테스크 상세 조회를 진행합니다.
         * @summary 프로젝트 테스크 상세 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectTask(clientProjectContractId: number, taskId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectMilestoneTaskResponse> {
            return localVarFp.getProjectTask(clientProjectContractId, taskId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 테스크의 히스토리 조회를 진행합니다.
         * @summary 프로젝트 마일스톤 테스크 히스토리 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectTaskHistory(clientProjectContractId: number, milestoneId: number, taskId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectMilestoneTaskHistoryListResponse> {
            return localVarFp.getProjectTaskHistory(clientProjectContractId, milestoneId, taskId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 테스크 진행률 조회를 진행합니다.
         * @summary 프로젝트 테스크 진행률 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} taskId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectTaskProgressPercent(clientProjectContractId: number, taskId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectTaskProgressPercentResponse> {
            return localVarFp.getProjectTaskProgressPercent(clientProjectContractId, taskId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 마일스톤 테스크의 산출물을 수정합니다.<br>수정을 원하는 값만 입력하고, 수정을 원하지 않는 값은 null로 보내주세요.
         * @summary 프로젝트 마일스톤 테스크 산출물 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {number} outputId 
         * @param {PatchProjectMilestoneTaskOutputRequest} patchProjectMilestoneTaskOutputRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectMilestoneTaskOutput(clientProjectContractId: number, milestoneId: number, taskId: number, outputId: number, patchProjectMilestoneTaskOutputRequest: PatchProjectMilestoneTaskOutputRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updateProjectMilestoneTaskOutput(clientProjectContractId, milestoneId, taskId, outputId, patchProjectMilestoneTaskOutputRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 테스크를 수정합니다.<br>변경되지 않은 기존 값도 모두 보내주어야 합니다.
         * @summary 프로젝트 마일스톤 테스크 수정 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {PutProjectMilestoneTaskRequest} putProjectMilestoneTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectTask(clientProjectContractId: number, milestoneId: number, taskId: number, putProjectMilestoneTaskRequest: PutProjectMilestoneTaskRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updateProjectTask(clientProjectContractId, milestoneId, taskId, putProjectMilestoneTaskRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 테스크의 상태를 변경합니다.
         * @summary 프로젝트 마일스톤 테스크 상태 변경 API
         * @param {number} clientProjectContractId 
         * @param {number} milestoneId 
         * @param {number} taskId 
         * @param {PatchProjectMilestoneTaskStatusRequest} patchProjectMilestoneTaskStatusRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateProjectTaskStatus(clientProjectContractId: number, milestoneId: number, taskId: number, patchProjectMilestoneTaskStatusRequest: PatchProjectMilestoneTaskStatusRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updateProjectTaskStatus(clientProjectContractId, milestoneId, taskId, patchProjectMilestoneTaskStatusRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectMilestoneTaskApi - object-oriented interface
 * @export
 * @class ProjectMilestoneTaskApi
 * @extends {BaseAPI}
 */
export class ProjectMilestoneTaskApi extends BaseAPI {
    /**
     * 프로젝트 마일스톤 테스크의 새로운 산출물을 등록합니다.
     * @summary 프로젝트 마일스톤 테스크 산출물 등록 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {number} taskId 
     * @param {PostProjectMilestoneTaskOutputRequest} postProjectMilestoneTaskOutputRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public createProjectMilestoneTaskOutput(clientProjectContractId: number, milestoneId: number, taskId: number, postProjectMilestoneTaskOutputRequest: PostProjectMilestoneTaskOutputRequest, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).createProjectMilestoneTaskOutput(clientProjectContractId, milestoneId, taskId, postProjectMilestoneTaskOutputRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 새로운 프로젝트 테스크를 생성합니다.
     * @summary 프로젝트 테스크 생성 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {PostProjectMilestoneTaskRequest} postProjectMilestoneTaskRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public createProjectTask(clientProjectContractId: number, milestoneId: number, postProjectMilestoneTaskRequest: PostProjectMilestoneTaskRequest, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).createProjectTask(clientProjectContractId, milestoneId, postProjectMilestoneTaskRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 기존 프로젝트 마일스톤 테스크를 삭제합니다.<br>이미 하위 작업 기록이 만들어져 있는 테스크는 삭제가 불가능합니다.
     * @summary 프로젝트 마일스톤 테스크 삭제 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {number} taskId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public deleteProjectMilestoneTask(clientProjectContractId: number, milestoneId: number, taskId: number, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).deleteProjectMilestoneTask(clientProjectContractId, milestoneId, taskId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 마일스톤 테스크의 산출물을 삭제합니다.
     * @summary 프로젝트 마일스톤 테스크 산출물 삭제 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {number} taskId 
     * @param {number} outputId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public deleteProjectMilestoneTaskOutput(clientProjectContractId: number, milestoneId: number, taskId: number, outputId: number, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).deleteProjectMilestoneTaskOutput(clientProjectContractId, milestoneId, taskId, outputId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 태스크 목록을 조회합니다.<br>milestoneId를 입력한 경우에는 마일스톤 하위에 생성된 테스크와 공통 테스크를 조회하고, milestoneId를 입력하지 않은 경우에는 마일스톤이 없는 공통 테스크만 조회합니다.<br>detail이 true인 경우 작업 상세 조회를 진행합니다.
     * @summary 프로젝트 테스크 목록 조회 API
     * @param {number} clientProjectContractId 
     * @param {boolean} detail 
     * @param {number} [milestoneId] 
     * @param {number} [projectWorkerId] 
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public getProjectMilestoneTasks(clientProjectContractId: number, detail: boolean, milestoneId?: number, projectWorkerId?: number, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).getProjectMilestoneTasks(clientProjectContractId, detail, milestoneId, projectWorkerId, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 테스크 상세 조회를 진행합니다.
     * @summary 프로젝트 테스크 상세 조회 API
     * @param {number} clientProjectContractId 
     * @param {number} taskId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public getProjectTask(clientProjectContractId: number, taskId: number, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).getProjectTask(clientProjectContractId, taskId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 테스크의 히스토리 조회를 진행합니다.
     * @summary 프로젝트 마일스톤 테스크 히스토리 조회 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {number} taskId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public getProjectTaskHistory(clientProjectContractId: number, milestoneId: number, taskId: number, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).getProjectTaskHistory(clientProjectContractId, milestoneId, taskId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 테스크 진행률 조회를 진행합니다.
     * @summary 프로젝트 테스크 진행률 조회 API
     * @param {number} clientProjectContractId 
     * @param {number} taskId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public getProjectTaskProgressPercent(clientProjectContractId: number, taskId: number, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).getProjectTaskProgressPercent(clientProjectContractId, taskId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 마일스톤 테스크의 산출물을 수정합니다.<br>수정을 원하는 값만 입력하고, 수정을 원하지 않는 값은 null로 보내주세요.
     * @summary 프로젝트 마일스톤 테스크 산출물 수정 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {number} taskId 
     * @param {number} outputId 
     * @param {PatchProjectMilestoneTaskOutputRequest} patchProjectMilestoneTaskOutputRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public updateProjectMilestoneTaskOutput(clientProjectContractId: number, milestoneId: number, taskId: number, outputId: number, patchProjectMilestoneTaskOutputRequest: PatchProjectMilestoneTaskOutputRequest, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).updateProjectMilestoneTaskOutput(clientProjectContractId, milestoneId, taskId, outputId, patchProjectMilestoneTaskOutputRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 테스크를 수정합니다.<br>변경되지 않은 기존 값도 모두 보내주어야 합니다.
     * @summary 프로젝트 마일스톤 테스크 수정 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {number} taskId 
     * @param {PutProjectMilestoneTaskRequest} putProjectMilestoneTaskRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public updateProjectTask(clientProjectContractId: number, milestoneId: number, taskId: number, putProjectMilestoneTaskRequest: PutProjectMilestoneTaskRequest, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).updateProjectTask(clientProjectContractId, milestoneId, taskId, putProjectMilestoneTaskRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 테스크의 상태를 변경합니다.
     * @summary 프로젝트 마일스톤 테스크 상태 변경 API
     * @param {number} clientProjectContractId 
     * @param {number} milestoneId 
     * @param {number} taskId 
     * @param {PatchProjectMilestoneTaskStatusRequest} patchProjectMilestoneTaskStatusRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectMilestoneTaskApi
     */
    public updateProjectTaskStatus(clientProjectContractId: number, milestoneId: number, taskId: number, patchProjectMilestoneTaskStatusRequest: PatchProjectMilestoneTaskStatusRequest, options?: RawAxiosRequestConfig) {
        return ProjectMilestoneTaskApiFp(this.configuration).updateProjectTaskStatus(clientProjectContractId, milestoneId, taskId, patchProjectMilestoneTaskStatusRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

