/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseGetProjectCntResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectContractListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectReportListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectRoleListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectWorkTimesResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectWorkerListResponse } from '../model';
/**
 * ProjectApi - axios parameter creator
 * @export
 */
export const ProjectApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 프로젝트 상태에 현재 사용자의 따른 프로젝트 개수를 조회합니다.
         * @summary 프로젝트 개수 조회 API
         * @param {GetProjectCntByStatusWorkerStatusEnum} workerStatus 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectCntByStatus: async (workerStatus: GetProjectCntByStatusWorkerStatusEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workerStatus' is not null or undefined
            assertParamExists('getProjectCntByStatus', 'workerStatus', workerStatus)
            const localVarPath = `/app/workers/projects/count`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (workerStatus !== undefined) {
                localVarQueryParameter['workerStatus'] = workerStatus;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 계약서 목록을 조회합니다.
         * @summary 프로젝트 계약서 목록 조회 API
         * @param {number} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectContracts: async (projectId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectId' is not null or undefined
            assertParamExists('getProjectContracts', 'projectId', projectId)
            const localVarPath = `/app/workers/projects/{projectId}/contracts`
                .replace(`{${"projectId"}}`, encodeURIComponent(String(projectId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트 보고서 목록을 조회합니다.
         * @summary 프로젝트 보고서 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectReports: async (clientProjectContractId: number, page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectReports', 'clientProjectContractId', clientProjectContractId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/reports`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트에 포함되는 직무 목록을 조회합니다.
         * @summary 프로젝트 직무 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectRoles: async (clientProjectContractId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectRoles', 'clientProjectContractId', clientProjectContractId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/roles`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 대시보드에서 프로젝트 전체 작업 시간과 이번 달 작업 시간을 조회합니다.
         * @summary 프로젝트 작업 시간 요약 조회 API
         * @param {number} projectWorkerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectWorkTimes: async (projectWorkerId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'projectWorkerId' is not null or undefined
            assertParamExists('getProjectWorkTimes', 'projectWorkerId', projectWorkerId)
            const localVarPath = `/app/workers/projects/{projectWorkerId}/work-times`
                .replace(`{${"projectWorkerId"}}`, encodeURIComponent(String(projectWorkerId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로젝트에 참여하는 작업자 목록을 조회합니다.
         * @summary 프로젝트 작업자 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectWorkers: async (clientProjectContractId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'clientProjectContractId' is not null or undefined
            assertParamExists('getProjectWorkers', 'clientProjectContractId', clientProjectContractId)
            const localVarPath = `/app/workers/projects/{clientProjectContractId}/project-workers`
                .replace(`{${"clientProjectContractId"}}`, encodeURIComponent(String(clientProjectContractId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 마이페이지에서 진행 프로젝트 목록을 조회합니다.
         * @summary 진행 프로젝트 목록 조회 API
         * @param {GetProjectsWorkerStatusEnum} workerStatus 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjects: async (workerStatus: GetProjectsWorkerStatusEnum, page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'workerStatus' is not null or undefined
            assertParamExists('getProjects', 'workerStatus', workerStatus)
            const localVarPath = `/app/workers/projects`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (workerStatus !== undefined) {
                localVarQueryParameter['workerStatus'] = workerStatus;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ProjectApi - functional programming interface
 * @export
 */
export const ProjectApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ProjectApiAxiosParamCreator(configuration)
    return {
        /**
         * 프로젝트 상태에 현재 사용자의 따른 프로젝트 개수를 조회합니다.
         * @summary 프로젝트 개수 조회 API
         * @param {GetProjectCntByStatusWorkerStatusEnum} workerStatus 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectCntByStatus(workerStatus: GetProjectCntByStatusWorkerStatusEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectCntResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectCntByStatus(workerStatus, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectApi.getProjectCntByStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 계약서 목록을 조회합니다.
         * @summary 프로젝트 계약서 목록 조회 API
         * @param {number} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectContracts(projectId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectContractListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectContracts(projectId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectApi.getProjectContracts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트 보고서 목록을 조회합니다.
         * @summary 프로젝트 보고서 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectReports(clientProjectContractId: number, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectReportListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectReports(clientProjectContractId, page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectApi.getProjectReports']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트에 포함되는 직무 목록을 조회합니다.
         * @summary 프로젝트 직무 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectRoles(clientProjectContractId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectRoleListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectRoles(clientProjectContractId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectApi.getProjectRoles']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 대시보드에서 프로젝트 전체 작업 시간과 이번 달 작업 시간을 조회합니다.
         * @summary 프로젝트 작업 시간 요약 조회 API
         * @param {number} projectWorkerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectWorkTimes(projectWorkerId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkTimesResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectWorkTimes(projectWorkerId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectApi.getProjectWorkTimes']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로젝트에 참여하는 작업자 목록을 조회합니다.
         * @summary 프로젝트 작업자 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjectWorkers(clientProjectContractId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkerListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjectWorkers(clientProjectContractId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectApi.getProjectWorkers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 마이페이지에서 진행 프로젝트 목록을 조회합니다.
         * @summary 진행 프로젝트 목록 조회 API
         * @param {GetProjectsWorkerStatusEnum} workerStatus 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getProjects(workerStatus: GetProjectsWorkerStatusEnum, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getProjects(workerStatus, page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ProjectApi.getProjects']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ProjectApi - factory interface
 * @export
 */
export const ProjectApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ProjectApiFp(configuration)
    return {
        /**
         * 프로젝트 상태에 현재 사용자의 따른 프로젝트 개수를 조회합니다.
         * @summary 프로젝트 개수 조회 API
         * @param {GetProjectCntByStatusWorkerStatusEnum} workerStatus 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectCntByStatus(workerStatus: GetProjectCntByStatusWorkerStatusEnum, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectCntResponse> {
            return localVarFp.getProjectCntByStatus(workerStatus, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 계약서 목록을 조회합니다.
         * @summary 프로젝트 계약서 목록 조회 API
         * @param {number} projectId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectContracts(projectId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectContractListResponse> {
            return localVarFp.getProjectContracts(projectId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트 보고서 목록을 조회합니다.
         * @summary 프로젝트 보고서 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectReports(clientProjectContractId: number, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectReportListResponse> {
            return localVarFp.getProjectReports(clientProjectContractId, page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트에 포함되는 직무 목록을 조회합니다.
         * @summary 프로젝트 직무 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectRoles(clientProjectContractId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectRoleListResponse> {
            return localVarFp.getProjectRoles(clientProjectContractId, options).then((request) => request(axios, basePath));
        },
        /**
         * 대시보드에서 프로젝트 전체 작업 시간과 이번 달 작업 시간을 조회합니다.
         * @summary 프로젝트 작업 시간 요약 조회 API
         * @param {number} projectWorkerId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectWorkTimes(projectWorkerId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkTimesResponse> {
            return localVarFp.getProjectWorkTimes(projectWorkerId, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로젝트에 참여하는 작업자 목록을 조회합니다.
         * @summary 프로젝트 작업자 목록 조회 API
         * @param {number} clientProjectContractId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjectWorkers(clientProjectContractId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkerListResponse> {
            return localVarFp.getProjectWorkers(clientProjectContractId, options).then((request) => request(axios, basePath));
        },
        /**
         * 마이페이지에서 진행 프로젝트 목록을 조회합니다.
         * @summary 진행 프로젝트 목록 조회 API
         * @param {GetProjectsWorkerStatusEnum} workerStatus 
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getProjects(workerStatus: GetProjectsWorkerStatusEnum, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectListResponse> {
            return localVarFp.getProjects(workerStatus, page, size, sort, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ProjectApi - object-oriented interface
 * @export
 * @class ProjectApi
 * @extends {BaseAPI}
 */
export class ProjectApi extends BaseAPI {
    /**
     * 프로젝트 상태에 현재 사용자의 따른 프로젝트 개수를 조회합니다.
     * @summary 프로젝트 개수 조회 API
     * @param {GetProjectCntByStatusWorkerStatusEnum} workerStatus 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApi
     */
    public getProjectCntByStatus(workerStatus: GetProjectCntByStatusWorkerStatusEnum, options?: RawAxiosRequestConfig) {
        return ProjectApiFp(this.configuration).getProjectCntByStatus(workerStatus, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 계약서 목록을 조회합니다.
     * @summary 프로젝트 계약서 목록 조회 API
     * @param {number} projectId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApi
     */
    public getProjectContracts(projectId: number, options?: RawAxiosRequestConfig) {
        return ProjectApiFp(this.configuration).getProjectContracts(projectId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트 보고서 목록을 조회합니다.
     * @summary 프로젝트 보고서 목록 조회 API
     * @param {number} clientProjectContractId 
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApi
     */
    public getProjectReports(clientProjectContractId: number, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig) {
        return ProjectApiFp(this.configuration).getProjectReports(clientProjectContractId, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트에 포함되는 직무 목록을 조회합니다.
     * @summary 프로젝트 직무 목록 조회 API
     * @param {number} clientProjectContractId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApi
     */
    public getProjectRoles(clientProjectContractId: number, options?: RawAxiosRequestConfig) {
        return ProjectApiFp(this.configuration).getProjectRoles(clientProjectContractId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 대시보드에서 프로젝트 전체 작업 시간과 이번 달 작업 시간을 조회합니다.
     * @summary 프로젝트 작업 시간 요약 조회 API
     * @param {number} projectWorkerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApi
     */
    public getProjectWorkTimes(projectWorkerId: number, options?: RawAxiosRequestConfig) {
        return ProjectApiFp(this.configuration).getProjectWorkTimes(projectWorkerId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로젝트에 참여하는 작업자 목록을 조회합니다.
     * @summary 프로젝트 작업자 목록 조회 API
     * @param {number} clientProjectContractId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApi
     */
    public getProjectWorkers(clientProjectContractId: number, options?: RawAxiosRequestConfig) {
        return ProjectApiFp(this.configuration).getProjectWorkers(clientProjectContractId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 마이페이지에서 진행 프로젝트 목록을 조회합니다.
     * @summary 진행 프로젝트 목록 조회 API
     * @param {GetProjectsWorkerStatusEnum} workerStatus 
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ProjectApi
     */
    public getProjects(workerStatus: GetProjectsWorkerStatusEnum, page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig) {
        return ProjectApiFp(this.configuration).getProjects(workerStatus, page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetProjectCntByStatusWorkerStatusEnum = {
    Wait: 'WAIT',
    InProgress: 'IN_PROGRESS',
    Complete: 'COMPLETE',
    Termination: 'TERMINATION'
} as const;
export type GetProjectCntByStatusWorkerStatusEnum = typeof GetProjectCntByStatusWorkerStatusEnum[keyof typeof GetProjectCntByStatusWorkerStatusEnum];
/**
 * @export
 */
export const GetProjectsWorkerStatusEnum = {
    Wait: 'WAIT',
    InProgress: 'IN_PROGRESS',
    Complete: 'COMPLETE',
    Termination: 'TERMINATION'
} as const;
export type GetProjectsWorkerStatusEnum = typeof GetProjectsWorkerStatusEnum[keyof typeof GetProjectsWorkerStatusEnum];
