/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApplyProjectWorkerRecruitmentRequest } from '../model';
// @ts-ignore
import type { BaseResponseApplyProjectWorkerRecruitmentResponse } from '../model';
// @ts-ignore
import type { BaseResponseBoolean } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectWorkerRecruitmentListResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetProjectWorkerRecruitmentResponse } from '../model';
/**
 * RecruitmentApi - axios parameter creator
 * @export
 */
export const RecruitmentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 긱워킹 공고를 통해 외주 공고에 지원합니다.
         * @summary 외주 공고 지원 API
         * @param {number} recruitmentId 
         * @param {ApplyProjectWorkerRecruitmentRequest} applyProjectWorkerRecruitmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        applyRecruitment: async (recruitmentId: number, applyProjectWorkerRecruitmentRequest: ApplyProjectWorkerRecruitmentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recruitmentId' is not null or undefined
            assertParamExists('applyRecruitment', 'recruitmentId', recruitmentId)
            // verify required parameter 'applyProjectWorkerRecruitmentRequest' is not null or undefined
            assertParamExists('applyRecruitment', 'applyProjectWorkerRecruitmentRequest', applyProjectWorkerRecruitmentRequest)
            const localVarPath = `/app/workers/project-recruitments/{recruitmentId}`
                .replace(`{${"recruitmentId"}}`, encodeURIComponent(String(recruitmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(applyProjectWorkerRecruitmentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 마이페이지에서 관심 프로젝트 목록을 조회합니다.
         * @summary 관심 프로젝트 목록 조회 API
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedRecruitment: async (page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/project-recruitments/interests`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 긱워킹 공고에서 외주 공고 상세 정보를 조회합니다.<br>회원/비회원 모두 가능합니다.
         * @summary 외주 공고 상세 조회 API
         * @param {number} recruitmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecruitment: async (recruitmentId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recruitmentId' is not null or undefined
            assertParamExists('getRecruitment', 'recruitmentId', recruitmentId)
            const localVarPath = `/app/workers/project-recruitments/{recruitmentId}`
                .replace(`{${"recruitmentId"}}`, encodeURIComponent(String(recruitmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 긱워킹 공고에서 직무 관련 프로젝트 목록을 조회합니다.
         * @summary 직무 관련 프로젝트 목록 조회 API
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecruitments: async (page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/project-recruitments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 긱워킹 공고에서 추천 프로젝트 목록을 조회합니다.<br>회원/비회원 모두 가능합니다.
         * @summary 추천 프로젝트 목록 조회 API
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSuggestedRecruitment: async (page?: number, size?: number, sort?: Array<string>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/project-recruitments/suggestions`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (size !== undefined) {
                localVarQueryParameter['size'] = size;
            }

            if (sort) {
                localVarQueryParameter['sort'] = sort;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 좋아요 버튼을 통해 외주 공고를 관심 프로젝트에 등록/삭제합니다.
         * @summary 관심 프로젝트 등록/삭제 API
         * @param {number} recruitmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        likeRecruitment: async (recruitmentId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'recruitmentId' is not null or undefined
            assertParamExists('likeRecruitment', 'recruitmentId', recruitmentId)
            const localVarPath = `/app/workers/project-recruitments/interests/{recruitmentId}`
                .replace(`{${"recruitmentId"}}`, encodeURIComponent(String(recruitmentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RecruitmentApi - functional programming interface
 * @export
 */
export const RecruitmentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RecruitmentApiAxiosParamCreator(configuration)
    return {
        /**
         * 긱워킹 공고를 통해 외주 공고에 지원합니다.
         * @summary 외주 공고 지원 API
         * @param {number} recruitmentId 
         * @param {ApplyProjectWorkerRecruitmentRequest} applyProjectWorkerRecruitmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async applyRecruitment(recruitmentId: number, applyProjectWorkerRecruitmentRequest: ApplyProjectWorkerRecruitmentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseApplyProjectWorkerRecruitmentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.applyRecruitment(recruitmentId, applyProjectWorkerRecruitmentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecruitmentApi.applyRecruitment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 마이페이지에서 관심 프로젝트 목록을 조회합니다.
         * @summary 관심 프로젝트 목록 조회 API
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLikedRecruitment(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkerRecruitmentListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLikedRecruitment(page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecruitmentApi.getLikedRecruitment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 긱워킹 공고에서 외주 공고 상세 정보를 조회합니다.<br>회원/비회원 모두 가능합니다.
         * @summary 외주 공고 상세 조회 API
         * @param {number} recruitmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRecruitment(recruitmentId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkerRecruitmentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRecruitment(recruitmentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecruitmentApi.getRecruitment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 긱워킹 공고에서 직무 관련 프로젝트 목록을 조회합니다.
         * @summary 직무 관련 프로젝트 목록 조회 API
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRecruitments(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkerRecruitmentListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRecruitments(page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecruitmentApi.getRecruitments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 긱워킹 공고에서 추천 프로젝트 목록을 조회합니다.<br>회원/비회원 모두 가능합니다.
         * @summary 추천 프로젝트 목록 조회 API
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getSuggestedRecruitment(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetProjectWorkerRecruitmentListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSuggestedRecruitment(page, size, sort, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecruitmentApi.getSuggestedRecruitment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 좋아요 버튼을 통해 외주 공고를 관심 프로젝트에 등록/삭제합니다.
         * @summary 관심 프로젝트 등록/삭제 API
         * @param {number} recruitmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async likeRecruitment(recruitmentId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.likeRecruitment(recruitmentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RecruitmentApi.likeRecruitment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RecruitmentApi - factory interface
 * @export
 */
export const RecruitmentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RecruitmentApiFp(configuration)
    return {
        /**
         * 긱워킹 공고를 통해 외주 공고에 지원합니다.
         * @summary 외주 공고 지원 API
         * @param {number} recruitmentId 
         * @param {ApplyProjectWorkerRecruitmentRequest} applyProjectWorkerRecruitmentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        applyRecruitment(recruitmentId: number, applyProjectWorkerRecruitmentRequest: ApplyProjectWorkerRecruitmentRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseApplyProjectWorkerRecruitmentResponse> {
            return localVarFp.applyRecruitment(recruitmentId, applyProjectWorkerRecruitmentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 마이페이지에서 관심 프로젝트 목록을 조회합니다.
         * @summary 관심 프로젝트 목록 조회 API
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLikedRecruitment(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkerRecruitmentListResponse> {
            return localVarFp.getLikedRecruitment(page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 긱워킹 공고에서 외주 공고 상세 정보를 조회합니다.<br>회원/비회원 모두 가능합니다.
         * @summary 외주 공고 상세 조회 API
         * @param {number} recruitmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecruitment(recruitmentId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkerRecruitmentResponse> {
            return localVarFp.getRecruitment(recruitmentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 긱워킹 공고에서 직무 관련 프로젝트 목록을 조회합니다.
         * @summary 직무 관련 프로젝트 목록 조회 API
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRecruitments(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkerRecruitmentListResponse> {
            return localVarFp.getRecruitments(page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 긱워킹 공고에서 추천 프로젝트 목록을 조회합니다.<br>회원/비회원 모두 가능합니다.
         * @summary 추천 프로젝트 목록 조회 API
         * @param {number} [page] Zero-based page index (0..N)
         * @param {number} [size] The size of the page to be returned
         * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getSuggestedRecruitment(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetProjectWorkerRecruitmentListResponse> {
            return localVarFp.getSuggestedRecruitment(page, size, sort, options).then((request) => request(axios, basePath));
        },
        /**
         * 좋아요 버튼을 통해 외주 공고를 관심 프로젝트에 등록/삭제합니다.
         * @summary 관심 프로젝트 등록/삭제 API
         * @param {number} recruitmentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        likeRecruitment(recruitmentId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.likeRecruitment(recruitmentId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RecruitmentApi - object-oriented interface
 * @export
 * @class RecruitmentApi
 * @extends {BaseAPI}
 */
export class RecruitmentApi extends BaseAPI {
    /**
     * 긱워킹 공고를 통해 외주 공고에 지원합니다.
     * @summary 외주 공고 지원 API
     * @param {number} recruitmentId 
     * @param {ApplyProjectWorkerRecruitmentRequest} applyProjectWorkerRecruitmentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApi
     */
    public applyRecruitment(recruitmentId: number, applyProjectWorkerRecruitmentRequest: ApplyProjectWorkerRecruitmentRequest, options?: RawAxiosRequestConfig) {
        return RecruitmentApiFp(this.configuration).applyRecruitment(recruitmentId, applyProjectWorkerRecruitmentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 마이페이지에서 관심 프로젝트 목록을 조회합니다.
     * @summary 관심 프로젝트 목록 조회 API
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApi
     */
    public getLikedRecruitment(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig) {
        return RecruitmentApiFp(this.configuration).getLikedRecruitment(page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 긱워킹 공고에서 외주 공고 상세 정보를 조회합니다.<br>회원/비회원 모두 가능합니다.
     * @summary 외주 공고 상세 조회 API
     * @param {number} recruitmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApi
     */
    public getRecruitment(recruitmentId: number, options?: RawAxiosRequestConfig) {
        return RecruitmentApiFp(this.configuration).getRecruitment(recruitmentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 긱워킹 공고에서 직무 관련 프로젝트 목록을 조회합니다.
     * @summary 직무 관련 프로젝트 목록 조회 API
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApi
     */
    public getRecruitments(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig) {
        return RecruitmentApiFp(this.configuration).getRecruitments(page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 긱워킹 공고에서 추천 프로젝트 목록을 조회합니다.<br>회원/비회원 모두 가능합니다.
     * @summary 추천 프로젝트 목록 조회 API
     * @param {number} [page] Zero-based page index (0..N)
     * @param {number} [size] The size of the page to be returned
     * @param {Array<string>} [sort] Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApi
     */
    public getSuggestedRecruitment(page?: number, size?: number, sort?: Array<string>, options?: RawAxiosRequestConfig) {
        return RecruitmentApiFp(this.configuration).getSuggestedRecruitment(page, size, sort, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 좋아요 버튼을 통해 외주 공고를 관심 프로젝트에 등록/삭제합니다.
     * @summary 관심 프로젝트 등록/삭제 API
     * @param {number} recruitmentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof RecruitmentApi
     */
    public likeRecruitment(recruitmentId: number, options?: RawAxiosRequestConfig) {
        return RecruitmentApiFp(this.configuration).likeRecruitment(recruitmentId, options).then((request) => request(this.axios, this.basePath));
    }
}

