/* tslint:disable */
/* eslint-disable */
/**
 * Gridge Worker API
 * Gridge 작업자 페이지 API 문서입니다.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { BaseResponseBoolean } from '../model';
// @ts-ignore
import type { BaseResponseCheckPhoneVerifyResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetUserDetailInfoResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetUserInfoResponse } from '../model';
// @ts-ignore
import type { BaseResponseGetUserRoleResponse } from '../model';
// @ts-ignore
import type { BaseResponsePostUserPortfolioResponse } from '../model';
// @ts-ignore
import type { BaseResponsePostUserProfileImgResponse } from '../model';
// @ts-ignore
import type { BaseResponseSendPhoneVerifyResponse } from '../model';
// @ts-ignore
import type { CheckPhoneVerifyRequest } from '../model';
// @ts-ignore
import type { PatchUserPasswordRequest } from '../model';
// @ts-ignore
import type { PostUserPortfolioRequest } from '../model';
// @ts-ignore
import type { PostUserProfileImgRequest } from '../model';
// @ts-ignore
import type { PutUserDetailInfoRequest } from '../model';
// @ts-ignore
import type { SendPhoneVerifyRequest } from '../model';
// @ts-ignore
import type { WithdrawUserRequest } from '../model';
/**
 * UserApi - axios parameter creator
 * @export
 */
export const UserApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 포트폴리오 파일을 S3에 업로드하기 위한 Pre-signed URL를 조회합니다.
         * @summary 포트폴리오 파일 업로드 PUT Pre-signed URL 조회 API
         * @param {PostUserPortfolioRequest} postUserPortfolioRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresignedUrlForPortfolio: async (postUserPortfolioRequest: PostUserPortfolioRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postUserPortfolioRequest' is not null or undefined
            assertParamExists('getPresignedUrlForPortfolio', 'postUserPortfolioRequest', postUserPortfolioRequest)
            const localVarPath = `/app/workers/portfolio`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postUserPortfolioRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 프로필 사진을 S3에 업로드하기 위한 Pre-signed URL를 조회합니다.
         * @summary 프로필 업로드 PUT Pre-signed URL 조회 API
         * @param {PostUserProfileImgRequest} postUserProfileImgRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresignedUrlForProfileImg: async (postUserProfileImgRequest: PostUserProfileImgRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'postUserProfileImgRequest' is not null or undefined
            assertParamExists('getPresignedUrlForProfileImg', 'postUserProfileImgRequest', postUserProfileImgRequest)
            const localVarPath = `/app/workers/profile-img`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(postUserProfileImgRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 유저의 상세 정보를 조회합니다.
         * @summary 유저 상세 정보 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserDetailInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/detail-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 유저의 정보를 조회합니다. (왼쪽 상단 프로필 부분)
         * @summary 유저 정보 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfo: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 유저의 상세 정보를 조회합니다.
         * @summary 유저 직무 목록 조회 API
         * @param {number} jobCategoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRoleList: async (jobCategoryId: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'jobCategoryId' is not null or undefined
            assertParamExists('getUserRoleList', 'jobCategoryId', jobCategoryId)
            const localVarPath = `/app/workers/role-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (jobCategoryId !== undefined) {
                localVarQueryParameter['jobCategoryId'] = jobCategoryId;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 작업자 로그아웃을 진행합니다.
         * @summary 작업자 로그아웃 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/app/workers/logout`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 휴대폰 인증 번호 알림톡 전송을 진행합니다.<br>만약 기존 휴대폰 번호와 같은 번호를 입력하면 알림톡이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
         * @summary 휴대폰 인증 번호 알림톡 전송 API
         * @param {SendPhoneVerifyRequest} sendPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendPhoneVerify: async (sendPhoneVerifyRequest: SendPhoneVerifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendPhoneVerifyRequest' is not null or undefined
            assertParamExists('sendPhoneVerify', 'sendPhoneVerifyRequest', sendPhoneVerifyRequest)
            const localVarPath = `/app/workers/phone-verify`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendPhoneVerifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 휴대폰 인증 번호 확인을 진행합니다.
         * @summary 휴대폰 인증 번호 확인 API
         * @param {CheckPhoneVerifyRequest} checkPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpPhoneVerify: async (checkPhoneVerifyRequest: CheckPhoneVerifyRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'checkPhoneVerifyRequest' is not null or undefined
            assertParamExists('signUpPhoneVerify', 'checkPhoneVerifyRequest', checkPhoneVerifyRequest)
            const localVarPath = `/app/workers/phone-verify/check`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(checkPhoneVerifyRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 비밀번호를 변경합니다.
         * @summary 비밀번호 변경 API
         * @param {PatchUserPasswordRequest} patchUserPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePassword1: async (patchUserPasswordRequest: PatchUserPasswordRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'patchUserPasswordRequest' is not null or undefined
            assertParamExists('updatePassword1', 'patchUserPasswordRequest', patchUserPasswordRequest)
            const localVarPath = `/app/workers/password`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchUserPasswordRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 유저의 상세 정보를 수정합니다.<br>전화번호를 따로 수정하지 않는 경우에는 verificationCode를 null로 보내주세요.
         * @summary 유저 정보 수정 API
         * @param {PutUserDetailInfoRequest} putUserDetailInfoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserDetailInfo: async (putUserDetailInfoRequest: PutUserDetailInfoRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'putUserDetailInfoRequest' is not null or undefined
            assertParamExists('updateUserDetailInfo', 'putUserDetailInfoRequest', putUserDetailInfoRequest)
            const localVarPath = `/app/workers/detail-info`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(putUserDetailInfoRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 회원 탈퇴를 진행합니다.
         * @summary 회원 탈퇴 API
         * @param {WithdrawUserRequest} withdrawUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        withdraw: async (withdrawUserRequest: WithdrawUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'withdrawUserRequest' is not null or undefined
            assertParamExists('withdraw', 'withdrawUserRequest', withdrawUserRequest)
            const localVarPath = `/app/workers/withdraw`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Access Token required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(withdrawUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserApi - functional programming interface
 * @export
 */
export const UserApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserApiAxiosParamCreator(configuration)
    return {
        /**
         * 포트폴리오 파일을 S3에 업로드하기 위한 Pre-signed URL를 조회합니다.
         * @summary 포트폴리오 파일 업로드 PUT Pre-signed URL 조회 API
         * @param {PostUserPortfolioRequest} postUserPortfolioRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPresignedUrlForPortfolio(postUserPortfolioRequest: PostUserPortfolioRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePostUserPortfolioResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPresignedUrlForPortfolio(postUserPortfolioRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getPresignedUrlForPortfolio']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 프로필 사진을 S3에 업로드하기 위한 Pre-signed URL를 조회합니다.
         * @summary 프로필 업로드 PUT Pre-signed URL 조회 API
         * @param {PostUserProfileImgRequest} postUserProfileImgRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getPresignedUrlForProfileImg(postUserProfileImgRequest: PostUserProfileImgRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponsePostUserProfileImgResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPresignedUrlForProfileImg(postUserProfileImgRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getPresignedUrlForProfileImg']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 유저의 상세 정보를 조회합니다.
         * @summary 유저 상세 정보 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserDetailInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetUserDetailInfoResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserDetailInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUserDetailInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 유저의 정보를 조회합니다. (왼쪽 상단 프로필 부분)
         * @summary 유저 정보 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserInfo(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetUserInfoResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserInfo(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUserInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 유저의 상세 정보를 조회합니다.
         * @summary 유저 직무 목록 조회 API
         * @param {number} jobCategoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUserRoleList(jobCategoryId: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseGetUserRoleResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUserRoleList(jobCategoryId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.getUserRoleList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 작업자 로그아웃을 진행합니다.
         * @summary 작업자 로그아웃 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async logout(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.logout(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.logout']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 휴대폰 인증 번호 알림톡 전송을 진행합니다.<br>만약 기존 휴대폰 번호와 같은 번호를 입력하면 알림톡이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
         * @summary 휴대폰 인증 번호 알림톡 전송 API
         * @param {SendPhoneVerifyRequest} sendPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async sendPhoneVerify(sendPhoneVerifyRequest: SendPhoneVerifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseSendPhoneVerifyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.sendPhoneVerify(sendPhoneVerifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.sendPhoneVerify']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 휴대폰 인증 번호 확인을 진행합니다.
         * @summary 휴대폰 인증 번호 확인 API
         * @param {CheckPhoneVerifyRequest} checkPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async signUpPhoneVerify(checkPhoneVerifyRequest: CheckPhoneVerifyRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseCheckPhoneVerifyResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.signUpPhoneVerify(checkPhoneVerifyRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.signUpPhoneVerify']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 비밀번호를 변경합니다.
         * @summary 비밀번호 변경 API
         * @param {PatchUserPasswordRequest} patchUserPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updatePassword1(patchUserPasswordRequest: PatchUserPasswordRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePassword1(patchUserPasswordRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.updatePassword1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 유저의 상세 정보를 수정합니다.<br>전화번호를 따로 수정하지 않는 경우에는 verificationCode를 null로 보내주세요.
         * @summary 유저 정보 수정 API
         * @param {PutUserDetailInfoRequest} putUserDetailInfoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUserDetailInfo(putUserDetailInfoRequest: PutUserDetailInfoRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUserDetailInfo(putUserDetailInfoRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.updateUserDetailInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 회원 탈퇴를 진행합니다.
         * @summary 회원 탈퇴 API
         * @param {WithdrawUserRequest} withdrawUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async withdraw(withdrawUserRequest: WithdrawUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaseResponseBoolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.withdraw(withdrawUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserApi.withdraw']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserApi - factory interface
 * @export
 */
export const UserApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserApiFp(configuration)
    return {
        /**
         * 포트폴리오 파일을 S3에 업로드하기 위한 Pre-signed URL를 조회합니다.
         * @summary 포트폴리오 파일 업로드 PUT Pre-signed URL 조회 API
         * @param {PostUserPortfolioRequest} postUserPortfolioRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresignedUrlForPortfolio(postUserPortfolioRequest: PostUserPortfolioRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePostUserPortfolioResponse> {
            return localVarFp.getPresignedUrlForPortfolio(postUserPortfolioRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 프로필 사진을 S3에 업로드하기 위한 Pre-signed URL를 조회합니다.
         * @summary 프로필 업로드 PUT Pre-signed URL 조회 API
         * @param {PostUserProfileImgRequest} postUserProfileImgRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getPresignedUrlForProfileImg(postUserProfileImgRequest: PostUserProfileImgRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponsePostUserProfileImgResponse> {
            return localVarFp.getPresignedUrlForProfileImg(postUserProfileImgRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 유저의 상세 정보를 조회합니다.
         * @summary 유저 상세 정보 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserDetailInfo(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetUserDetailInfoResponse> {
            return localVarFp.getUserDetailInfo(options).then((request) => request(axios, basePath));
        },
        /**
         * 유저의 정보를 조회합니다. (왼쪽 상단 프로필 부분)
         * @summary 유저 정보 조회 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserInfo(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetUserInfoResponse> {
            return localVarFp.getUserInfo(options).then((request) => request(axios, basePath));
        },
        /**
         * 유저의 상세 정보를 조회합니다.
         * @summary 유저 직무 목록 조회 API
         * @param {number} jobCategoryId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUserRoleList(jobCategoryId: number, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseGetUserRoleResponse> {
            return localVarFp.getUserRoleList(jobCategoryId, options).then((request) => request(axios, basePath));
        },
        /**
         * 작업자 로그아웃을 진행합니다.
         * @summary 작업자 로그아웃 API
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        logout(options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.logout(options).then((request) => request(axios, basePath));
        },
        /**
         * 휴대폰 인증 번호 알림톡 전송을 진행합니다.<br>만약 기존 휴대폰 번호와 같은 번호를 입력하면 알림톡이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
         * @summary 휴대폰 인증 번호 알림톡 전송 API
         * @param {SendPhoneVerifyRequest} sendPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        sendPhoneVerify(sendPhoneVerifyRequest: SendPhoneVerifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseSendPhoneVerifyResponse> {
            return localVarFp.sendPhoneVerify(sendPhoneVerifyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 휴대폰 인증 번호 확인을 진행합니다.
         * @summary 휴대폰 인증 번호 확인 API
         * @param {CheckPhoneVerifyRequest} checkPhoneVerifyRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        signUpPhoneVerify(checkPhoneVerifyRequest: CheckPhoneVerifyRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseCheckPhoneVerifyResponse> {
            return localVarFp.signUpPhoneVerify(checkPhoneVerifyRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 비밀번호를 변경합니다.
         * @summary 비밀번호 변경 API
         * @param {PatchUserPasswordRequest} patchUserPasswordRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updatePassword1(patchUserPasswordRequest: PatchUserPasswordRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updatePassword1(patchUserPasswordRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 유저의 상세 정보를 수정합니다.<br>전화번호를 따로 수정하지 않는 경우에는 verificationCode를 null로 보내주세요.
         * @summary 유저 정보 수정 API
         * @param {PutUserDetailInfoRequest} putUserDetailInfoRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUserDetailInfo(putUserDetailInfoRequest: PutUserDetailInfoRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.updateUserDetailInfo(putUserDetailInfoRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 회원 탈퇴를 진행합니다.
         * @summary 회원 탈퇴 API
         * @param {WithdrawUserRequest} withdrawUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        withdraw(withdrawUserRequest: WithdrawUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<BaseResponseBoolean> {
            return localVarFp.withdraw(withdrawUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserApi - object-oriented interface
 * @export
 * @class UserApi
 * @extends {BaseAPI}
 */
export class UserApi extends BaseAPI {
    /**
     * 포트폴리오 파일을 S3에 업로드하기 위한 Pre-signed URL를 조회합니다.
     * @summary 포트폴리오 파일 업로드 PUT Pre-signed URL 조회 API
     * @param {PostUserPortfolioRequest} postUserPortfolioRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getPresignedUrlForPortfolio(postUserPortfolioRequest: PostUserPortfolioRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getPresignedUrlForPortfolio(postUserPortfolioRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 프로필 사진을 S3에 업로드하기 위한 Pre-signed URL를 조회합니다.
     * @summary 프로필 업로드 PUT Pre-signed URL 조회 API
     * @param {PostUserProfileImgRequest} postUserProfileImgRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getPresignedUrlForProfileImg(postUserProfileImgRequest: PostUserProfileImgRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getPresignedUrlForProfileImg(postUserProfileImgRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 유저의 상세 정보를 조회합니다.
     * @summary 유저 상세 정보 조회 API
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUserDetailInfo(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserDetailInfo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 유저의 정보를 조회합니다. (왼쪽 상단 프로필 부분)
     * @summary 유저 정보 조회 API
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUserInfo(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserInfo(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 유저의 상세 정보를 조회합니다.
     * @summary 유저 직무 목록 조회 API
     * @param {number} jobCategoryId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public getUserRoleList(jobCategoryId: number, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).getUserRoleList(jobCategoryId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 작업자 로그아웃을 진행합니다.
     * @summary 작업자 로그아웃 API
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public logout(options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).logout(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 휴대폰 인증 번호 알림톡 전송을 진행합니다.<br>만약 기존 휴대폰 번호와 같은 번호를 입력하면 알림톡이 전송되지 않으며, 전송 결과가 false로 반환됩니다.
     * @summary 휴대폰 인증 번호 알림톡 전송 API
     * @param {SendPhoneVerifyRequest} sendPhoneVerifyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public sendPhoneVerify(sendPhoneVerifyRequest: SendPhoneVerifyRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).sendPhoneVerify(sendPhoneVerifyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 휴대폰 인증 번호 확인을 진행합니다.
     * @summary 휴대폰 인증 번호 확인 API
     * @param {CheckPhoneVerifyRequest} checkPhoneVerifyRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public signUpPhoneVerify(checkPhoneVerifyRequest: CheckPhoneVerifyRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).signUpPhoneVerify(checkPhoneVerifyRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 비밀번호를 변경합니다.
     * @summary 비밀번호 변경 API
     * @param {PatchUserPasswordRequest} patchUserPasswordRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public updatePassword1(patchUserPasswordRequest: PatchUserPasswordRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).updatePassword1(patchUserPasswordRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 유저의 상세 정보를 수정합니다.<br>전화번호를 따로 수정하지 않는 경우에는 verificationCode를 null로 보내주세요.
     * @summary 유저 정보 수정 API
     * @param {PutUserDetailInfoRequest} putUserDetailInfoRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public updateUserDetailInfo(putUserDetailInfoRequest: PutUserDetailInfoRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).updateUserDetailInfo(putUserDetailInfoRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 회원 탈퇴를 진행합니다.
     * @summary 회원 탈퇴 API
     * @param {WithdrawUserRequest} withdrawUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UserApi
     */
    public withdraw(withdrawUserRequest: WithdrawUserRequest, options?: RawAxiosRequestConfig) {
        return UserApiFp(this.configuration).withdraw(withdrawUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

